// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pg_layout.proto

package new_object_builder_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LayoutService_CreateAll_FullMethodName       = "/new_object_builder_service.LayoutService/CreateAll"
	LayoutService_Update_FullMethodName          = "/new_object_builder_service.LayoutService/Update"
	LayoutService_GetAll_FullMethodName          = "/new_object_builder_service.LayoutService/GetAll"
	LayoutService_GetSingleLayout_FullMethodName = "/new_object_builder_service.LayoutService/GetSingleLayout"
	LayoutService_RemoveLayout_FullMethodName    = "/new_object_builder_service.LayoutService/RemoveLayout"
	LayoutService_GetByID_FullMethodName         = "/new_object_builder_service.LayoutService/GetByID"
)

// LayoutServiceClient is the client API for LayoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LayoutServiceClient interface {
	CreateAll(ctx context.Context, in *CreateLayoutRequest, opts ...grpc.CallOption) (*GetListLayoutResponse, error)
	Update(ctx context.Context, in *LayoutRequest, opts ...grpc.CallOption) (*LayoutResponse, error)
	GetAll(ctx context.Context, in *GetListLayoutRequest, opts ...grpc.CallOption) (*GetListLayoutResponse, error)
	GetSingleLayout(ctx context.Context, in *GetSingleLayoutRequest, opts ...grpc.CallOption) (*LayoutResponse, error)
	RemoveLayout(ctx context.Context, in *LayoutPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
	GetByID(ctx context.Context, in *LayoutPrimaryKey, opts ...grpc.CallOption) (*LayoutResponse, error)
}

type layoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLayoutServiceClient(cc grpc.ClientConnInterface) LayoutServiceClient {
	return &layoutServiceClient{cc}
}

func (c *layoutServiceClient) CreateAll(ctx context.Context, in *CreateLayoutRequest, opts ...grpc.CallOption) (*GetListLayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListLayoutResponse)
	err := c.cc.Invoke(ctx, LayoutService_CreateAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) Update(ctx context.Context, in *LayoutRequest, opts ...grpc.CallOption) (*LayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LayoutResponse)
	err := c.cc.Invoke(ctx, LayoutService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) GetAll(ctx context.Context, in *GetListLayoutRequest, opts ...grpc.CallOption) (*GetListLayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListLayoutResponse)
	err := c.cc.Invoke(ctx, LayoutService_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) GetSingleLayout(ctx context.Context, in *GetSingleLayoutRequest, opts ...grpc.CallOption) (*LayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LayoutResponse)
	err := c.cc.Invoke(ctx, LayoutService_GetSingleLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) RemoveLayout(ctx context.Context, in *LayoutPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, LayoutService_RemoveLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) GetByID(ctx context.Context, in *LayoutPrimaryKey, opts ...grpc.CallOption) (*LayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LayoutResponse)
	err := c.cc.Invoke(ctx, LayoutService_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LayoutServiceServer is the server API for LayoutService service.
// All implementations must embed UnimplementedLayoutServiceServer
// for forward compatibility.
type LayoutServiceServer interface {
	CreateAll(context.Context, *CreateLayoutRequest) (*GetListLayoutResponse, error)
	Update(context.Context, *LayoutRequest) (*LayoutResponse, error)
	GetAll(context.Context, *GetListLayoutRequest) (*GetListLayoutResponse, error)
	GetSingleLayout(context.Context, *GetSingleLayoutRequest) (*LayoutResponse, error)
	RemoveLayout(context.Context, *LayoutPrimaryKey) (*empty.Empty, error)
	GetByID(context.Context, *LayoutPrimaryKey) (*LayoutResponse, error)
	mustEmbedUnimplementedLayoutServiceServer()
}

// UnimplementedLayoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLayoutServiceServer struct{}

func (UnimplementedLayoutServiceServer) CreateAll(context.Context, *CreateLayoutRequest) (*GetListLayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAll not implemented")
}
func (UnimplementedLayoutServiceServer) Update(context.Context, *LayoutRequest) (*LayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedLayoutServiceServer) GetAll(context.Context, *GetListLayoutRequest) (*GetListLayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedLayoutServiceServer) GetSingleLayout(context.Context, *GetSingleLayoutRequest) (*LayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingleLayout not implemented")
}
func (UnimplementedLayoutServiceServer) RemoveLayout(context.Context, *LayoutPrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveLayout not implemented")
}
func (UnimplementedLayoutServiceServer) GetByID(context.Context, *LayoutPrimaryKey) (*LayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedLayoutServiceServer) mustEmbedUnimplementedLayoutServiceServer() {}
func (UnimplementedLayoutServiceServer) testEmbeddedByValue()                       {}

// UnsafeLayoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LayoutServiceServer will
// result in compilation errors.
type UnsafeLayoutServiceServer interface {
	mustEmbedUnimplementedLayoutServiceServer()
}

func RegisterLayoutServiceServer(s grpc.ServiceRegistrar, srv LayoutServiceServer) {
	// If the following call pancis, it indicates UnimplementedLayoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LayoutService_ServiceDesc, srv)
}

func _LayoutService_CreateAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).CreateAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_CreateAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).CreateAll(ctx, req.(*CreateLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).Update(ctx, req.(*LayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).GetAll(ctx, req.(*GetListLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_GetSingleLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSingleLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).GetSingleLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_GetSingleLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).GetSingleLayout(ctx, req.(*GetSingleLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_RemoveLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LayoutPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).RemoveLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_RemoveLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).RemoveLayout(ctx, req.(*LayoutPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LayoutPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).GetByID(ctx, req.(*LayoutPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// LayoutService_ServiceDesc is the grpc.ServiceDesc for LayoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LayoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "new_object_builder_service.LayoutService",
	HandlerType: (*LayoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAll",
			Handler:    _LayoutService_CreateAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _LayoutService_Update_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _LayoutService_GetAll_Handler,
		},
		{
			MethodName: "GetSingleLayout",
			Handler:    _LayoutService_GetSingleLayout_Handler,
		},
		{
			MethodName: "RemoveLayout",
			Handler:    _LayoutService_RemoveLayout_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _LayoutService_GetByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pg_layout.proto",
}
