// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pg_login.proto

package new_object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoginService_LoginData_FullMethodName           = "/new_object_builder_service.LoginService/LoginData"
	LoginService_GetConnetionOptions_FullMethodName = "/new_object_builder_service.LoginService/GetConnetionOptions"
)

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginServiceClient interface {
	// rpc Login (LoginRequest) returns (V2LoginResponse) {}
	LoginData(ctx context.Context, in *LoginDataReq, opts ...grpc.CallOption) (*LoginDataRes, error)
	// rpc LoginWithOtp (PhoneOtpRequst) returns (V2LoginResponse) {}
	// rpc LoginWithEmailOtp (EmailOtpRequest) returns (V2LoginResponse) {}
	// rpc GetUserUpdatedPermission (GetUserUpdatedPermissionRequest) returns(V2LoginResponse) {}
	// rpc LoginDataByUserId (LoginDataReq) returns (LoginDataRes) {}
	GetConnetionOptions(ctx context.Context, in *GetConnetionOptionsRequest, opts ...grpc.CallOption) (*GetConnectionOptionsResponse, error)
}

type loginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginServiceClient(cc grpc.ClientConnInterface) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) LoginData(ctx context.Context, in *LoginDataReq, opts ...grpc.CallOption) (*LoginDataRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginDataRes)
	err := c.cc.Invoke(ctx, LoginService_LoginData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) GetConnetionOptions(ctx context.Context, in *GetConnetionOptionsRequest, opts ...grpc.CallOption) (*GetConnectionOptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionOptionsResponse)
	err := c.cc.Invoke(ctx, LoginService_GetConnetionOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
// All implementations must embed UnimplementedLoginServiceServer
// for forward compatibility.
type LoginServiceServer interface {
	// rpc Login (LoginRequest) returns (V2LoginResponse) {}
	LoginData(context.Context, *LoginDataReq) (*LoginDataRes, error)
	// rpc LoginWithOtp (PhoneOtpRequst) returns (V2LoginResponse) {}
	// rpc LoginWithEmailOtp (EmailOtpRequest) returns (V2LoginResponse) {}
	// rpc GetUserUpdatedPermission (GetUserUpdatedPermissionRequest) returns(V2LoginResponse) {}
	// rpc LoginDataByUserId (LoginDataReq) returns (LoginDataRes) {}
	GetConnetionOptions(context.Context, *GetConnetionOptionsRequest) (*GetConnectionOptionsResponse, error)
	mustEmbedUnimplementedLoginServiceServer()
}

// UnimplementedLoginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginServiceServer struct{}

func (UnimplementedLoginServiceServer) LoginData(context.Context, *LoginDataReq) (*LoginDataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginData not implemented")
}
func (UnimplementedLoginServiceServer) GetConnetionOptions(context.Context, *GetConnetionOptionsRequest) (*GetConnectionOptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnetionOptions not implemented")
}
func (UnimplementedLoginServiceServer) mustEmbedUnimplementedLoginServiceServer() {}
func (UnimplementedLoginServiceServer) testEmbeddedByValue()                      {}

// UnsafeLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginServiceServer will
// result in compilation errors.
type UnsafeLoginServiceServer interface {
	mustEmbedUnimplementedLoginServiceServer()
}

func RegisterLoginServiceServer(s grpc.ServiceRegistrar, srv LoginServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoginService_ServiceDesc, srv)
}

func _LoginService_LoginData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).LoginData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_LoginData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).LoginData(ctx, req.(*LoginDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_GetConnetionOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnetionOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).GetConnetionOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_GetConnetionOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).GetConnetionOptions(ctx, req.(*GetConnetionOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginService_ServiceDesc is the grpc.ServiceDesc for LoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "new_object_builder_service.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginData",
			Handler:    _LoginService_LoginData_Handler,
		},
		{
			MethodName: "GetConnetionOptions",
			Handler:    _LoginService_GetConnetionOptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pg_login.proto",
}
