// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: menu.proto

package object_builder_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MenuService_Create_FullMethodName              = "/object_builder_service.MenuService/Create"
	MenuService_GetByID_FullMethodName             = "/object_builder_service.MenuService/GetByID"
	MenuService_GetByLabel_FullMethodName          = "/object_builder_service.MenuService/GetByLabel"
	MenuService_GetAll_FullMethodName              = "/object_builder_service.MenuService/GetAll"
	MenuService_Update_FullMethodName              = "/object_builder_service.MenuService/Update"
	MenuService_Delete_FullMethodName              = "/object_builder_service.MenuService/Delete"
	MenuService_UpdateMenuOrder_FullMethodName     = "/object_builder_service.MenuService/UpdateMenuOrder"
	MenuService_CreateMenuSettings_FullMethodName  = "/object_builder_service.MenuService/CreateMenuSettings"
	MenuService_GetAllMenuSettings_FullMethodName  = "/object_builder_service.MenuService/GetAllMenuSettings"
	MenuService_GetByIDMenuSettings_FullMethodName = "/object_builder_service.MenuService/GetByIDMenuSettings"
	MenuService_UpdateMenuSettings_FullMethodName  = "/object_builder_service.MenuService/UpdateMenuSettings"
	MenuService_DeleteMenuSettings_FullMethodName  = "/object_builder_service.MenuService/DeleteMenuSettings"
	MenuService_CreateMenuTemplate_FullMethodName  = "/object_builder_service.MenuService/CreateMenuTemplate"
	MenuService_GetAllMenuTemplate_FullMethodName  = "/object_builder_service.MenuService/GetAllMenuTemplate"
	MenuService_GetByIDMenuTemplate_FullMethodName = "/object_builder_service.MenuService/GetByIDMenuTemplate"
	MenuService_UpdateMenuTemplate_FullMethodName  = "/object_builder_service.MenuService/UpdateMenuTemplate"
	MenuService_DeleteMenuTemplate_FullMethodName  = "/object_builder_service.MenuService/DeleteMenuTemplate"
	MenuService_GetWikiFolder_FullMethodName       = "/object_builder_service.MenuService/GetWikiFolder"
)

// MenuServiceClient is the client API for MenuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MenuServiceClient interface {
	Create(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*Menu, error)
	GetByID(ctx context.Context, in *MenuPrimaryKey, opts ...grpc.CallOption) (*Menu, error)
	GetByLabel(ctx context.Context, in *MenuPrimaryKey, opts ...grpc.CallOption) (*GetAllMenusResponse, error)
	GetAll(ctx context.Context, in *GetAllMenusRequest, opts ...grpc.CallOption) (*GetAllMenusResponse, error)
	Update(ctx context.Context, in *Menu, opts ...grpc.CallOption) (*Menu, error)
	Delete(ctx context.Context, in *MenuPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateMenuOrder(ctx context.Context, in *UpdateMenuOrderRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateMenuSettings(ctx context.Context, in *CreateMenuSettingsRequest, opts ...grpc.CallOption) (*MenuSettings, error)
	GetAllMenuSettings(ctx context.Context, in *GetAllMenuSettingsRequest, opts ...grpc.CallOption) (*GetAllMenuSettingsResponse, error)
	GetByIDMenuSettings(ctx context.Context, in *MenuSettingPrimaryKey, opts ...grpc.CallOption) (*MenuSettings, error)
	UpdateMenuSettings(ctx context.Context, in *UpdateMenuSettingsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteMenuSettings(ctx context.Context, in *MenuSettingPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateMenuTemplate(ctx context.Context, in *CreateMenuTemplateRequest, opts ...grpc.CallOption) (*MenuTemplate, error)
	GetAllMenuTemplate(ctx context.Context, in *GetAllMenuSettingsRequest, opts ...grpc.CallOption) (*GatAllMenuTemplateResponse, error)
	GetByIDMenuTemplate(ctx context.Context, in *MenuSettingPrimaryKey, opts ...grpc.CallOption) (*MenuTemplate, error)
	UpdateMenuTemplate(ctx context.Context, in *UpdateMenuTemplateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteMenuTemplate(ctx context.Context, in *MenuSettingPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
	GetWikiFolder(ctx context.Context, in *GetWikiFolderRequest, opts ...grpc.CallOption) (*GetAllMenusResponse, error)
}

type menuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMenuServiceClient(cc grpc.ClientConnInterface) MenuServiceClient {
	return &menuServiceClient{cc}
}

func (c *menuServiceClient) Create(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*Menu, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Menu)
	err := c.cc.Invoke(ctx, MenuService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) GetByID(ctx context.Context, in *MenuPrimaryKey, opts ...grpc.CallOption) (*Menu, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Menu)
	err := c.cc.Invoke(ctx, MenuService_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) GetByLabel(ctx context.Context, in *MenuPrimaryKey, opts ...grpc.CallOption) (*GetAllMenusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMenusResponse)
	err := c.cc.Invoke(ctx, MenuService_GetByLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) GetAll(ctx context.Context, in *GetAllMenusRequest, opts ...grpc.CallOption) (*GetAllMenusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMenusResponse)
	err := c.cc.Invoke(ctx, MenuService_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) Update(ctx context.Context, in *Menu, opts ...grpc.CallOption) (*Menu, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Menu)
	err := c.cc.Invoke(ctx, MenuService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) Delete(ctx context.Context, in *MenuPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, MenuService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) UpdateMenuOrder(ctx context.Context, in *UpdateMenuOrderRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, MenuService_UpdateMenuOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) CreateMenuSettings(ctx context.Context, in *CreateMenuSettingsRequest, opts ...grpc.CallOption) (*MenuSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuSettings)
	err := c.cc.Invoke(ctx, MenuService_CreateMenuSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) GetAllMenuSettings(ctx context.Context, in *GetAllMenuSettingsRequest, opts ...grpc.CallOption) (*GetAllMenuSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMenuSettingsResponse)
	err := c.cc.Invoke(ctx, MenuService_GetAllMenuSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) GetByIDMenuSettings(ctx context.Context, in *MenuSettingPrimaryKey, opts ...grpc.CallOption) (*MenuSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuSettings)
	err := c.cc.Invoke(ctx, MenuService_GetByIDMenuSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) UpdateMenuSettings(ctx context.Context, in *UpdateMenuSettingsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, MenuService_UpdateMenuSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) DeleteMenuSettings(ctx context.Context, in *MenuSettingPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, MenuService_DeleteMenuSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) CreateMenuTemplate(ctx context.Context, in *CreateMenuTemplateRequest, opts ...grpc.CallOption) (*MenuTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuTemplate)
	err := c.cc.Invoke(ctx, MenuService_CreateMenuTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) GetAllMenuTemplate(ctx context.Context, in *GetAllMenuSettingsRequest, opts ...grpc.CallOption) (*GatAllMenuTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatAllMenuTemplateResponse)
	err := c.cc.Invoke(ctx, MenuService_GetAllMenuTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) GetByIDMenuTemplate(ctx context.Context, in *MenuSettingPrimaryKey, opts ...grpc.CallOption) (*MenuTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuTemplate)
	err := c.cc.Invoke(ctx, MenuService_GetByIDMenuTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) UpdateMenuTemplate(ctx context.Context, in *UpdateMenuTemplateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, MenuService_UpdateMenuTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) DeleteMenuTemplate(ctx context.Context, in *MenuSettingPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, MenuService_DeleteMenuTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) GetWikiFolder(ctx context.Context, in *GetWikiFolderRequest, opts ...grpc.CallOption) (*GetAllMenusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMenusResponse)
	err := c.cc.Invoke(ctx, MenuService_GetWikiFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MenuServiceServer is the server API for MenuService service.
// All implementations must embed UnimplementedMenuServiceServer
// for forward compatibility.
type MenuServiceServer interface {
	Create(context.Context, *CreateMenuRequest) (*Menu, error)
	GetByID(context.Context, *MenuPrimaryKey) (*Menu, error)
	GetByLabel(context.Context, *MenuPrimaryKey) (*GetAllMenusResponse, error)
	GetAll(context.Context, *GetAllMenusRequest) (*GetAllMenusResponse, error)
	Update(context.Context, *Menu) (*Menu, error)
	Delete(context.Context, *MenuPrimaryKey) (*empty.Empty, error)
	UpdateMenuOrder(context.Context, *UpdateMenuOrderRequest) (*empty.Empty, error)
	CreateMenuSettings(context.Context, *CreateMenuSettingsRequest) (*MenuSettings, error)
	GetAllMenuSettings(context.Context, *GetAllMenuSettingsRequest) (*GetAllMenuSettingsResponse, error)
	GetByIDMenuSettings(context.Context, *MenuSettingPrimaryKey) (*MenuSettings, error)
	UpdateMenuSettings(context.Context, *UpdateMenuSettingsRequest) (*empty.Empty, error)
	DeleteMenuSettings(context.Context, *MenuSettingPrimaryKey) (*empty.Empty, error)
	CreateMenuTemplate(context.Context, *CreateMenuTemplateRequest) (*MenuTemplate, error)
	GetAllMenuTemplate(context.Context, *GetAllMenuSettingsRequest) (*GatAllMenuTemplateResponse, error)
	GetByIDMenuTemplate(context.Context, *MenuSettingPrimaryKey) (*MenuTemplate, error)
	UpdateMenuTemplate(context.Context, *UpdateMenuTemplateRequest) (*empty.Empty, error)
	DeleteMenuTemplate(context.Context, *MenuSettingPrimaryKey) (*empty.Empty, error)
	GetWikiFolder(context.Context, *GetWikiFolderRequest) (*GetAllMenusResponse, error)
	mustEmbedUnimplementedMenuServiceServer()
}

// UnimplementedMenuServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMenuServiceServer struct{}

func (UnimplementedMenuServiceServer) Create(context.Context, *CreateMenuRequest) (*Menu, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedMenuServiceServer) GetByID(context.Context, *MenuPrimaryKey) (*Menu, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedMenuServiceServer) GetByLabel(context.Context, *MenuPrimaryKey) (*GetAllMenusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByLabel not implemented")
}
func (UnimplementedMenuServiceServer) GetAll(context.Context, *GetAllMenusRequest) (*GetAllMenusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedMenuServiceServer) Update(context.Context, *Menu) (*Menu, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedMenuServiceServer) Delete(context.Context, *MenuPrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedMenuServiceServer) UpdateMenuOrder(context.Context, *UpdateMenuOrderRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMenuOrder not implemented")
}
func (UnimplementedMenuServiceServer) CreateMenuSettings(context.Context, *CreateMenuSettingsRequest) (*MenuSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMenuSettings not implemented")
}
func (UnimplementedMenuServiceServer) GetAllMenuSettings(context.Context, *GetAllMenuSettingsRequest) (*GetAllMenuSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMenuSettings not implemented")
}
func (UnimplementedMenuServiceServer) GetByIDMenuSettings(context.Context, *MenuSettingPrimaryKey) (*MenuSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIDMenuSettings not implemented")
}
func (UnimplementedMenuServiceServer) UpdateMenuSettings(context.Context, *UpdateMenuSettingsRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMenuSettings not implemented")
}
func (UnimplementedMenuServiceServer) DeleteMenuSettings(context.Context, *MenuSettingPrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMenuSettings not implemented")
}
func (UnimplementedMenuServiceServer) CreateMenuTemplate(context.Context, *CreateMenuTemplateRequest) (*MenuTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMenuTemplate not implemented")
}
func (UnimplementedMenuServiceServer) GetAllMenuTemplate(context.Context, *GetAllMenuSettingsRequest) (*GatAllMenuTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMenuTemplate not implemented")
}
func (UnimplementedMenuServiceServer) GetByIDMenuTemplate(context.Context, *MenuSettingPrimaryKey) (*MenuTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIDMenuTemplate not implemented")
}
func (UnimplementedMenuServiceServer) UpdateMenuTemplate(context.Context, *UpdateMenuTemplateRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMenuTemplate not implemented")
}
func (UnimplementedMenuServiceServer) DeleteMenuTemplate(context.Context, *MenuSettingPrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMenuTemplate not implemented")
}
func (UnimplementedMenuServiceServer) GetWikiFolder(context.Context, *GetWikiFolderRequest) (*GetAllMenusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWikiFolder not implemented")
}
func (UnimplementedMenuServiceServer) mustEmbedUnimplementedMenuServiceServer() {}
func (UnimplementedMenuServiceServer) testEmbeddedByValue()                     {}

// UnsafeMenuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MenuServiceServer will
// result in compilation errors.
type UnsafeMenuServiceServer interface {
	mustEmbedUnimplementedMenuServiceServer()
}

func RegisterMenuServiceServer(s grpc.ServiceRegistrar, srv MenuServiceServer) {
	// If the following call pancis, it indicates UnimplementedMenuServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MenuService_ServiceDesc, srv)
}

func _MenuService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).Create(ctx, req.(*CreateMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).GetByID(ctx, req.(*MenuPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_GetByLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).GetByLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_GetByLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).GetByLabel(ctx, req.(*MenuPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMenusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).GetAll(ctx, req.(*GetAllMenusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Menu)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).Update(ctx, req.(*Menu))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).Delete(ctx, req.(*MenuPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_UpdateMenuOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMenuOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).UpdateMenuOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_UpdateMenuOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).UpdateMenuOrder(ctx, req.(*UpdateMenuOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_CreateMenuSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMenuSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).CreateMenuSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_CreateMenuSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).CreateMenuSettings(ctx, req.(*CreateMenuSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_GetAllMenuSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMenuSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).GetAllMenuSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_GetAllMenuSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).GetAllMenuSettings(ctx, req.(*GetAllMenuSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_GetByIDMenuSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuSettingPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).GetByIDMenuSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_GetByIDMenuSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).GetByIDMenuSettings(ctx, req.(*MenuSettingPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_UpdateMenuSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMenuSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).UpdateMenuSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_UpdateMenuSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).UpdateMenuSettings(ctx, req.(*UpdateMenuSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_DeleteMenuSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuSettingPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).DeleteMenuSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_DeleteMenuSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).DeleteMenuSettings(ctx, req.(*MenuSettingPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_CreateMenuTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMenuTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).CreateMenuTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_CreateMenuTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).CreateMenuTemplate(ctx, req.(*CreateMenuTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_GetAllMenuTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMenuSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).GetAllMenuTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_GetAllMenuTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).GetAllMenuTemplate(ctx, req.(*GetAllMenuSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_GetByIDMenuTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuSettingPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).GetByIDMenuTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_GetByIDMenuTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).GetByIDMenuTemplate(ctx, req.(*MenuSettingPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_UpdateMenuTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMenuTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).UpdateMenuTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_UpdateMenuTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).UpdateMenuTemplate(ctx, req.(*UpdateMenuTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_DeleteMenuTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuSettingPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).DeleteMenuTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_DeleteMenuTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).DeleteMenuTemplate(ctx, req.(*MenuSettingPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_GetWikiFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWikiFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).GetWikiFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_GetWikiFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).GetWikiFolder(ctx, req.(*GetWikiFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MenuService_ServiceDesc is the grpc.ServiceDesc for MenuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MenuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.MenuService",
	HandlerType: (*MenuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _MenuService_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _MenuService_GetByID_Handler,
		},
		{
			MethodName: "GetByLabel",
			Handler:    _MenuService_GetByLabel_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _MenuService_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MenuService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MenuService_Delete_Handler,
		},
		{
			MethodName: "UpdateMenuOrder",
			Handler:    _MenuService_UpdateMenuOrder_Handler,
		},
		{
			MethodName: "CreateMenuSettings",
			Handler:    _MenuService_CreateMenuSettings_Handler,
		},
		{
			MethodName: "GetAllMenuSettings",
			Handler:    _MenuService_GetAllMenuSettings_Handler,
		},
		{
			MethodName: "GetByIDMenuSettings",
			Handler:    _MenuService_GetByIDMenuSettings_Handler,
		},
		{
			MethodName: "UpdateMenuSettings",
			Handler:    _MenuService_UpdateMenuSettings_Handler,
		},
		{
			MethodName: "DeleteMenuSettings",
			Handler:    _MenuService_DeleteMenuSettings_Handler,
		},
		{
			MethodName: "CreateMenuTemplate",
			Handler:    _MenuService_CreateMenuTemplate_Handler,
		},
		{
			MethodName: "GetAllMenuTemplate",
			Handler:    _MenuService_GetAllMenuTemplate_Handler,
		},
		{
			MethodName: "GetByIDMenuTemplate",
			Handler:    _MenuService_GetByIDMenuTemplate_Handler,
		},
		{
			MethodName: "UpdateMenuTemplate",
			Handler:    _MenuService_UpdateMenuTemplate_Handler,
		},
		{
			MethodName: "DeleteMenuTemplate",
			Handler:    _MenuService_DeleteMenuTemplate_Handler,
		},
		{
			MethodName: "GetWikiFolder",
			Handler:    _MenuService_GetWikiFolder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "menu.proto",
}
