// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: report_setting_service.proto

package object_builder_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReportSettingService_GetByIdReportSetting_FullMethodName = "/object_builder_service.ReportSettingService/GetByIdReportSetting"
	ReportSettingService_GetListReportSetting_FullMethodName = "/object_builder_service.ReportSettingService/GetListReportSetting"
	ReportSettingService_UpsertReportSetting_FullMethodName  = "/object_builder_service.ReportSettingService/UpsertReportSetting"
	ReportSettingService_DeleteReportSetting_FullMethodName  = "/object_builder_service.ReportSettingService/DeleteReportSetting"
	ReportSettingService_SavePivotTemplate_FullMethodName    = "/object_builder_service.ReportSettingService/SavePivotTemplate"
	ReportSettingService_GetByIdPivotTemplate_FullMethodName = "/object_builder_service.ReportSettingService/GetByIdPivotTemplate"
	ReportSettingService_GetListPivotTemplate_FullMethodName = "/object_builder_service.ReportSettingService/GetListPivotTemplate"
	ReportSettingService_UpsertPivotTemplate_FullMethodName  = "/object_builder_service.ReportSettingService/UpsertPivotTemplate"
	ReportSettingService_RemovePivotTemplate_FullMethodName  = "/object_builder_service.ReportSettingService/RemovePivotTemplate"
)

// ReportSettingServiceClient is the client API for ReportSettingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportSettingServiceClient interface {
	GetByIdReportSetting(ctx context.Context, in *AppReportSettingPrimaryKey, opts ...grpc.CallOption) (*AppReportSetting, error)
	GetListReportSetting(ctx context.Context, in *GetListReportSettingRequest, opts ...grpc.CallOption) (*GetListReportSettingResponse, error)
	UpsertReportSetting(ctx context.Context, in *UpsertAppReportSettingRequest, opts ...grpc.CallOption) (*AppReportSetting, error)
	DeleteReportSetting(ctx context.Context, in *AppReportSettingPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
	SavePivotTemplate(ctx context.Context, in *SavePivotTemplateRequest, opts ...grpc.CallOption) (*PivotTemplateSetting, error)
	GetByIdPivotTemplate(ctx context.Context, in *PivotTemplatePrimaryKey, opts ...grpc.CallOption) (*PivotTemplateSetting, error)
	GetListPivotTemplate(ctx context.Context, in *GetListPivotTemplateRequest, opts ...grpc.CallOption) (*GetListPivotTemplateResponse, error)
	UpsertPivotTemplate(ctx context.Context, in *PivotTemplateSetting, opts ...grpc.CallOption) (*PivotTemplateSetting, error)
	RemovePivotTemplate(ctx context.Context, in *RemovePivotTemplateSettingRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type reportSettingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportSettingServiceClient(cc grpc.ClientConnInterface) ReportSettingServiceClient {
	return &reportSettingServiceClient{cc}
}

func (c *reportSettingServiceClient) GetByIdReportSetting(ctx context.Context, in *AppReportSettingPrimaryKey, opts ...grpc.CallOption) (*AppReportSetting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppReportSetting)
	err := c.cc.Invoke(ctx, ReportSettingService_GetByIdReportSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportSettingServiceClient) GetListReportSetting(ctx context.Context, in *GetListReportSettingRequest, opts ...grpc.CallOption) (*GetListReportSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListReportSettingResponse)
	err := c.cc.Invoke(ctx, ReportSettingService_GetListReportSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportSettingServiceClient) UpsertReportSetting(ctx context.Context, in *UpsertAppReportSettingRequest, opts ...grpc.CallOption) (*AppReportSetting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppReportSetting)
	err := c.cc.Invoke(ctx, ReportSettingService_UpsertReportSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportSettingServiceClient) DeleteReportSetting(ctx context.Context, in *AppReportSettingPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, ReportSettingService_DeleteReportSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportSettingServiceClient) SavePivotTemplate(ctx context.Context, in *SavePivotTemplateRequest, opts ...grpc.CallOption) (*PivotTemplateSetting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PivotTemplateSetting)
	err := c.cc.Invoke(ctx, ReportSettingService_SavePivotTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportSettingServiceClient) GetByIdPivotTemplate(ctx context.Context, in *PivotTemplatePrimaryKey, opts ...grpc.CallOption) (*PivotTemplateSetting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PivotTemplateSetting)
	err := c.cc.Invoke(ctx, ReportSettingService_GetByIdPivotTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportSettingServiceClient) GetListPivotTemplate(ctx context.Context, in *GetListPivotTemplateRequest, opts ...grpc.CallOption) (*GetListPivotTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListPivotTemplateResponse)
	err := c.cc.Invoke(ctx, ReportSettingService_GetListPivotTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportSettingServiceClient) UpsertPivotTemplate(ctx context.Context, in *PivotTemplateSetting, opts ...grpc.CallOption) (*PivotTemplateSetting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PivotTemplateSetting)
	err := c.cc.Invoke(ctx, ReportSettingService_UpsertPivotTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportSettingServiceClient) RemovePivotTemplate(ctx context.Context, in *RemovePivotTemplateSettingRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, ReportSettingService_RemovePivotTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportSettingServiceServer is the server API for ReportSettingService service.
// All implementations must embed UnimplementedReportSettingServiceServer
// for forward compatibility.
type ReportSettingServiceServer interface {
	GetByIdReportSetting(context.Context, *AppReportSettingPrimaryKey) (*AppReportSetting, error)
	GetListReportSetting(context.Context, *GetListReportSettingRequest) (*GetListReportSettingResponse, error)
	UpsertReportSetting(context.Context, *UpsertAppReportSettingRequest) (*AppReportSetting, error)
	DeleteReportSetting(context.Context, *AppReportSettingPrimaryKey) (*empty.Empty, error)
	SavePivotTemplate(context.Context, *SavePivotTemplateRequest) (*PivotTemplateSetting, error)
	GetByIdPivotTemplate(context.Context, *PivotTemplatePrimaryKey) (*PivotTemplateSetting, error)
	GetListPivotTemplate(context.Context, *GetListPivotTemplateRequest) (*GetListPivotTemplateResponse, error)
	UpsertPivotTemplate(context.Context, *PivotTemplateSetting) (*PivotTemplateSetting, error)
	RemovePivotTemplate(context.Context, *RemovePivotTemplateSettingRequest) (*empty.Empty, error)
	mustEmbedUnimplementedReportSettingServiceServer()
}

// UnimplementedReportSettingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportSettingServiceServer struct{}

func (UnimplementedReportSettingServiceServer) GetByIdReportSetting(context.Context, *AppReportSettingPrimaryKey) (*AppReportSetting, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIdReportSetting not implemented")
}
func (UnimplementedReportSettingServiceServer) GetListReportSetting(context.Context, *GetListReportSettingRequest) (*GetListReportSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListReportSetting not implemented")
}
func (UnimplementedReportSettingServiceServer) UpsertReportSetting(context.Context, *UpsertAppReportSettingRequest) (*AppReportSetting, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertReportSetting not implemented")
}
func (UnimplementedReportSettingServiceServer) DeleteReportSetting(context.Context, *AppReportSettingPrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReportSetting not implemented")
}
func (UnimplementedReportSettingServiceServer) SavePivotTemplate(context.Context, *SavePivotTemplateRequest) (*PivotTemplateSetting, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SavePivotTemplate not implemented")
}
func (UnimplementedReportSettingServiceServer) GetByIdPivotTemplate(context.Context, *PivotTemplatePrimaryKey) (*PivotTemplateSetting, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIdPivotTemplate not implemented")
}
func (UnimplementedReportSettingServiceServer) GetListPivotTemplate(context.Context, *GetListPivotTemplateRequest) (*GetListPivotTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListPivotTemplate not implemented")
}
func (UnimplementedReportSettingServiceServer) UpsertPivotTemplate(context.Context, *PivotTemplateSetting) (*PivotTemplateSetting, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertPivotTemplate not implemented")
}
func (UnimplementedReportSettingServiceServer) RemovePivotTemplate(context.Context, *RemovePivotTemplateSettingRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePivotTemplate not implemented")
}
func (UnimplementedReportSettingServiceServer) mustEmbedUnimplementedReportSettingServiceServer() {}
func (UnimplementedReportSettingServiceServer) testEmbeddedByValue()                              {}

// UnsafeReportSettingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportSettingServiceServer will
// result in compilation errors.
type UnsafeReportSettingServiceServer interface {
	mustEmbedUnimplementedReportSettingServiceServer()
}

func RegisterReportSettingServiceServer(s grpc.ServiceRegistrar, srv ReportSettingServiceServer) {
	// If the following call pancis, it indicates UnimplementedReportSettingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReportSettingService_ServiceDesc, srv)
}

func _ReportSettingService_GetByIdReportSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppReportSettingPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSettingServiceServer).GetByIdReportSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportSettingService_GetByIdReportSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSettingServiceServer).GetByIdReportSetting(ctx, req.(*AppReportSettingPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportSettingService_GetListReportSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListReportSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSettingServiceServer).GetListReportSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportSettingService_GetListReportSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSettingServiceServer).GetListReportSetting(ctx, req.(*GetListReportSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportSettingService_UpsertReportSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertAppReportSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSettingServiceServer).UpsertReportSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportSettingService_UpsertReportSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSettingServiceServer).UpsertReportSetting(ctx, req.(*UpsertAppReportSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportSettingService_DeleteReportSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppReportSettingPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSettingServiceServer).DeleteReportSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportSettingService_DeleteReportSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSettingServiceServer).DeleteReportSetting(ctx, req.(*AppReportSettingPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportSettingService_SavePivotTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavePivotTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSettingServiceServer).SavePivotTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportSettingService_SavePivotTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSettingServiceServer).SavePivotTemplate(ctx, req.(*SavePivotTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportSettingService_GetByIdPivotTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PivotTemplatePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSettingServiceServer).GetByIdPivotTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportSettingService_GetByIdPivotTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSettingServiceServer).GetByIdPivotTemplate(ctx, req.(*PivotTemplatePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportSettingService_GetListPivotTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListPivotTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSettingServiceServer).GetListPivotTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportSettingService_GetListPivotTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSettingServiceServer).GetListPivotTemplate(ctx, req.(*GetListPivotTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportSettingService_UpsertPivotTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PivotTemplateSetting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSettingServiceServer).UpsertPivotTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportSettingService_UpsertPivotTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSettingServiceServer).UpsertPivotTemplate(ctx, req.(*PivotTemplateSetting))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportSettingService_RemovePivotTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePivotTemplateSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSettingServiceServer).RemovePivotTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportSettingService_RemovePivotTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSettingServiceServer).RemovePivotTemplate(ctx, req.(*RemovePivotTemplateSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportSettingService_ServiceDesc is the grpc.ServiceDesc for ReportSettingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportSettingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.ReportSettingService",
	HandlerType: (*ReportSettingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByIdReportSetting",
			Handler:    _ReportSettingService_GetByIdReportSetting_Handler,
		},
		{
			MethodName: "GetListReportSetting",
			Handler:    _ReportSettingService_GetListReportSetting_Handler,
		},
		{
			MethodName: "UpsertReportSetting",
			Handler:    _ReportSettingService_UpsertReportSetting_Handler,
		},
		{
			MethodName: "DeleteReportSetting",
			Handler:    _ReportSettingService_DeleteReportSetting_Handler,
		},
		{
			MethodName: "SavePivotTemplate",
			Handler:    _ReportSettingService_SavePivotTemplate_Handler,
		},
		{
			MethodName: "GetByIdPivotTemplate",
			Handler:    _ReportSettingService_GetByIdPivotTemplate_Handler,
		},
		{
			MethodName: "GetListPivotTemplate",
			Handler:    _ReportSettingService_GetListPivotTemplate_Handler,
		},
		{
			MethodName: "UpsertPivotTemplate",
			Handler:    _ReportSettingService_UpsertPivotTemplate_Handler,
		},
		{
			MethodName: "RemovePivotTemplate",
			Handler:    _ReportSettingService_RemovePivotTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report_setting_service.proto",
}
