// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: request_analytic.proto

package object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequestAnalyticService_Create_FullMethodName    = "/object_builder_service.RequestAnalyticService/Create"
	RequestAnalyticService_GetSingle_FullMethodName = "/object_builder_service.RequestAnalyticService/GetSingle"
	RequestAnalyticService_GetList_FullMethodName   = "/object_builder_service.RequestAnalyticService/GetList"
)

// RequestAnalyticServiceClient is the client API for RequestAnalyticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RequestAnalyticServiceClient interface {
	Create(ctx context.Context, in *CreateRequestAnalytic, opts ...grpc.CallOption) (*RequestAnalytic, error)
	GetSingle(ctx context.Context, in *RequestAnalyticPrimaryKey, opts ...grpc.CallOption) (*RequestAnalytic, error)
	GetList(ctx context.Context, in *GetAllRequestAnalyticRequest, opts ...grpc.CallOption) (*GetAllRequestAnalyticResponse, error)
}

type requestAnalyticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestAnalyticServiceClient(cc grpc.ClientConnInterface) RequestAnalyticServiceClient {
	return &requestAnalyticServiceClient{cc}
}

func (c *requestAnalyticServiceClient) Create(ctx context.Context, in *CreateRequestAnalytic, opts ...grpc.CallOption) (*RequestAnalytic, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestAnalytic)
	err := c.cc.Invoke(ctx, RequestAnalyticService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestAnalyticServiceClient) GetSingle(ctx context.Context, in *RequestAnalyticPrimaryKey, opts ...grpc.CallOption) (*RequestAnalytic, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestAnalytic)
	err := c.cc.Invoke(ctx, RequestAnalyticService_GetSingle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestAnalyticServiceClient) GetList(ctx context.Context, in *GetAllRequestAnalyticRequest, opts ...grpc.CallOption) (*GetAllRequestAnalyticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllRequestAnalyticResponse)
	err := c.cc.Invoke(ctx, RequestAnalyticService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestAnalyticServiceServer is the server API for RequestAnalyticService service.
// All implementations must embed UnimplementedRequestAnalyticServiceServer
// for forward compatibility.
type RequestAnalyticServiceServer interface {
	Create(context.Context, *CreateRequestAnalytic) (*RequestAnalytic, error)
	GetSingle(context.Context, *RequestAnalyticPrimaryKey) (*RequestAnalytic, error)
	GetList(context.Context, *GetAllRequestAnalyticRequest) (*GetAllRequestAnalyticResponse, error)
	mustEmbedUnimplementedRequestAnalyticServiceServer()
}

// UnimplementedRequestAnalyticServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequestAnalyticServiceServer struct{}

func (UnimplementedRequestAnalyticServiceServer) Create(context.Context, *CreateRequestAnalytic) (*RequestAnalytic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRequestAnalyticServiceServer) GetSingle(context.Context, *RequestAnalyticPrimaryKey) (*RequestAnalytic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingle not implemented")
}
func (UnimplementedRequestAnalyticServiceServer) GetList(context.Context, *GetAllRequestAnalyticRequest) (*GetAllRequestAnalyticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedRequestAnalyticServiceServer) mustEmbedUnimplementedRequestAnalyticServiceServer() {
}
func (UnimplementedRequestAnalyticServiceServer) testEmbeddedByValue() {}

// UnsafeRequestAnalyticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequestAnalyticServiceServer will
// result in compilation errors.
type UnsafeRequestAnalyticServiceServer interface {
	mustEmbedUnimplementedRequestAnalyticServiceServer()
}

func RegisterRequestAnalyticServiceServer(s grpc.ServiceRegistrar, srv RequestAnalyticServiceServer) {
	// If the following call pancis, it indicates UnimplementedRequestAnalyticServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequestAnalyticService_ServiceDesc, srv)
}

func _RequestAnalyticService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequestAnalytic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestAnalyticServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestAnalyticService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestAnalyticServiceServer).Create(ctx, req.(*CreateRequestAnalytic))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestAnalyticService_GetSingle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAnalyticPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestAnalyticServiceServer).GetSingle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestAnalyticService_GetSingle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestAnalyticServiceServer).GetSingle(ctx, req.(*RequestAnalyticPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestAnalyticService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequestAnalyticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestAnalyticServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestAnalyticService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestAnalyticServiceServer).GetList(ctx, req.(*GetAllRequestAnalyticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequestAnalyticService_ServiceDesc is the grpc.ServiceDesc for RequestAnalyticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequestAnalyticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.RequestAnalyticService",
	HandlerType: (*RequestAnalyticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _RequestAnalyticService_Create_Handler,
		},
		{
			MethodName: "GetSingle",
			Handler:    _RequestAnalyticService_GetSingle_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _RequestAnalyticService_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "request_analytic.proto",
}
