// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: section.proto

package object_builder_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SectionService_GetAll_FullMethodName              = "/object_builder_service.SectionService/GetAll"
	SectionService_Update_FullMethodName              = "/object_builder_service.SectionService/Update"
	SectionService_GetAllViewRelations_FullMethodName = "/object_builder_service.SectionService/GetAllViewRelations"
	SectionService_GetViewRelation_FullMethodName     = "/object_builder_service.SectionService/GetViewRelation"
	SectionService_UpsertViewRelations_FullMethodName = "/object_builder_service.SectionService/UpsertViewRelations"
)

// SectionServiceClient is the client API for SectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SectionServiceClient interface {
	GetAll(ctx context.Context, in *GetAllSectionsRequest, opts ...grpc.CallOption) (*GetAllSectionsResponse, error)
	Update(ctx context.Context, in *UpdateSectionsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetAllViewRelations(ctx context.Context, in *GetAllSectionsRequest, opts ...grpc.CallOption) (*GetAllViewRelationsResponse, error)
	GetViewRelation(ctx context.Context, in *GetAllSectionsRequest, opts ...grpc.CallOption) (*GetViewRelationResponse, error)
	UpsertViewRelations(ctx context.Context, in *UpsertViewRelationsBody, opts ...grpc.CallOption) (*empty.Empty, error)
}

type sectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSectionServiceClient(cc grpc.ClientConnInterface) SectionServiceClient {
	return &sectionServiceClient{cc}
}

func (c *sectionServiceClient) GetAll(ctx context.Context, in *GetAllSectionsRequest, opts ...grpc.CallOption) (*GetAllSectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllSectionsResponse)
	err := c.cc.Invoke(ctx, SectionService_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sectionServiceClient) Update(ctx context.Context, in *UpdateSectionsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SectionService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sectionServiceClient) GetAllViewRelations(ctx context.Context, in *GetAllSectionsRequest, opts ...grpc.CallOption) (*GetAllViewRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllViewRelationsResponse)
	err := c.cc.Invoke(ctx, SectionService_GetAllViewRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sectionServiceClient) GetViewRelation(ctx context.Context, in *GetAllSectionsRequest, opts ...grpc.CallOption) (*GetViewRelationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetViewRelationResponse)
	err := c.cc.Invoke(ctx, SectionService_GetViewRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sectionServiceClient) UpsertViewRelations(ctx context.Context, in *UpsertViewRelationsBody, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SectionService_UpsertViewRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SectionServiceServer is the server API for SectionService service.
// All implementations must embed UnimplementedSectionServiceServer
// for forward compatibility.
type SectionServiceServer interface {
	GetAll(context.Context, *GetAllSectionsRequest) (*GetAllSectionsResponse, error)
	Update(context.Context, *UpdateSectionsRequest) (*empty.Empty, error)
	GetAllViewRelations(context.Context, *GetAllSectionsRequest) (*GetAllViewRelationsResponse, error)
	GetViewRelation(context.Context, *GetAllSectionsRequest) (*GetViewRelationResponse, error)
	UpsertViewRelations(context.Context, *UpsertViewRelationsBody) (*empty.Empty, error)
	mustEmbedUnimplementedSectionServiceServer()
}

// UnimplementedSectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSectionServiceServer struct{}

func (UnimplementedSectionServiceServer) GetAll(context.Context, *GetAllSectionsRequest) (*GetAllSectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedSectionServiceServer) Update(context.Context, *UpdateSectionsRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSectionServiceServer) GetAllViewRelations(context.Context, *GetAllSectionsRequest) (*GetAllViewRelationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllViewRelations not implemented")
}
func (UnimplementedSectionServiceServer) GetViewRelation(context.Context, *GetAllSectionsRequest) (*GetViewRelationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetViewRelation not implemented")
}
func (UnimplementedSectionServiceServer) UpsertViewRelations(context.Context, *UpsertViewRelationsBody) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertViewRelations not implemented")
}
func (UnimplementedSectionServiceServer) mustEmbedUnimplementedSectionServiceServer() {}
func (UnimplementedSectionServiceServer) testEmbeddedByValue()                        {}

// UnsafeSectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SectionServiceServer will
// result in compilation errors.
type UnsafeSectionServiceServer interface {
	mustEmbedUnimplementedSectionServiceServer()
}

func RegisterSectionServiceServer(s grpc.ServiceRegistrar, srv SectionServiceServer) {
	// If the following call pancis, it indicates UnimplementedSectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SectionService_ServiceDesc, srv)
}

func _SectionService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SectionServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SectionService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SectionServiceServer).GetAll(ctx, req.(*GetAllSectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SectionService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SectionServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SectionService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SectionServiceServer).Update(ctx, req.(*UpdateSectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SectionService_GetAllViewRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SectionServiceServer).GetAllViewRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SectionService_GetAllViewRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SectionServiceServer).GetAllViewRelations(ctx, req.(*GetAllSectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SectionService_GetViewRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SectionServiceServer).GetViewRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SectionService_GetViewRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SectionServiceServer).GetViewRelation(ctx, req.(*GetAllSectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SectionService_UpsertViewRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertViewRelationsBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SectionServiceServer).UpsertViewRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SectionService_UpsertViewRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SectionServiceServer).UpsertViewRelations(ctx, req.(*UpsertViewRelationsBody))
	}
	return interceptor(ctx, in, info, handler)
}

// SectionService_ServiceDesc is the grpc.ServiceDesc for SectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.SectionService",
	HandlerType: (*SectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _SectionService_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SectionService_Update_Handler,
		},
		{
			MethodName: "GetAllViewRelations",
			Handler:    _SectionService_GetAllViewRelations_Handler,
		},
		{
			MethodName: "GetViewRelation",
			Handler:    _SectionService_GetViewRelation_Handler,
		},
		{
			MethodName: "UpsertViewRelations",
			Handler:    _SectionService_UpsertViewRelations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "section.proto",
}
