// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: version_history.proto

package object_builder_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VersionHistoryService_Create_FullMethodName  = "/object_builder_service.VersionHistoryService/Create"
	VersionHistoryService_GatAll_FullMethodName  = "/object_builder_service.VersionHistoryService/GatAll"
	VersionHistoryService_Update_FullMethodName  = "/object_builder_service.VersionHistoryService/Update"
	VersionHistoryService_GetByID_FullMethodName = "/object_builder_service.VersionHistoryService/GetByID"
)

// VersionHistoryServiceClient is the client API for VersionHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VersionHistoryServiceClient interface {
	Create(ctx context.Context, in *CreateVersionHistoryRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GatAll(ctx context.Context, in *GetAllRquest, opts ...grpc.CallOption) (*ListVersionHistory, error)
	Update(ctx context.Context, in *UsedForEnvRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetByID(ctx context.Context, in *VersionHistoryPrimaryKey, opts ...grpc.CallOption) (*VersionHistory, error)
}

type versionHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVersionHistoryServiceClient(cc grpc.ClientConnInterface) VersionHistoryServiceClient {
	return &versionHistoryServiceClient{cc}
}

func (c *versionHistoryServiceClient) Create(ctx context.Context, in *CreateVersionHistoryRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, VersionHistoryService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionHistoryServiceClient) GatAll(ctx context.Context, in *GetAllRquest, opts ...grpc.CallOption) (*ListVersionHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVersionHistory)
	err := c.cc.Invoke(ctx, VersionHistoryService_GatAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionHistoryServiceClient) Update(ctx context.Context, in *UsedForEnvRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, VersionHistoryService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionHistoryServiceClient) GetByID(ctx context.Context, in *VersionHistoryPrimaryKey, opts ...grpc.CallOption) (*VersionHistory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionHistory)
	err := c.cc.Invoke(ctx, VersionHistoryService_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersionHistoryServiceServer is the server API for VersionHistoryService service.
// All implementations must embed UnimplementedVersionHistoryServiceServer
// for forward compatibility.
type VersionHistoryServiceServer interface {
	Create(context.Context, *CreateVersionHistoryRequest) (*empty.Empty, error)
	GatAll(context.Context, *GetAllRquest) (*ListVersionHistory, error)
	Update(context.Context, *UsedForEnvRequest) (*empty.Empty, error)
	GetByID(context.Context, *VersionHistoryPrimaryKey) (*VersionHistory, error)
	mustEmbedUnimplementedVersionHistoryServiceServer()
}

// UnimplementedVersionHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVersionHistoryServiceServer struct{}

func (UnimplementedVersionHistoryServiceServer) Create(context.Context, *CreateVersionHistoryRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedVersionHistoryServiceServer) GatAll(context.Context, *GetAllRquest) (*ListVersionHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatAll not implemented")
}
func (UnimplementedVersionHistoryServiceServer) Update(context.Context, *UsedForEnvRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedVersionHistoryServiceServer) GetByID(context.Context, *VersionHistoryPrimaryKey) (*VersionHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedVersionHistoryServiceServer) mustEmbedUnimplementedVersionHistoryServiceServer() {}
func (UnimplementedVersionHistoryServiceServer) testEmbeddedByValue()                               {}

// UnsafeVersionHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VersionHistoryServiceServer will
// result in compilation errors.
type UnsafeVersionHistoryServiceServer interface {
	mustEmbedUnimplementedVersionHistoryServiceServer()
}

func RegisterVersionHistoryServiceServer(s grpc.ServiceRegistrar, srv VersionHistoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedVersionHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VersionHistoryService_ServiceDesc, srv)
}

func _VersionHistoryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVersionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionHistoryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionHistoryService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionHistoryServiceServer).Create(ctx, req.(*CreateVersionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionHistoryService_GatAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionHistoryServiceServer).GatAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionHistoryService_GatAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionHistoryServiceServer).GatAll(ctx, req.(*GetAllRquest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionHistoryService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsedForEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionHistoryServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionHistoryService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionHistoryServiceServer).Update(ctx, req.(*UsedForEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionHistoryService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionHistoryPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionHistoryServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionHistoryService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionHistoryServiceServer).GetByID(ctx, req.(*VersionHistoryPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// VersionHistoryService_ServiceDesc is the grpc.ServiceDesc for VersionHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VersionHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.VersionHistoryService",
	HandlerType: (*VersionHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _VersionHistoryService_Create_Handler,
		},
		{
			MethodName: "GatAll",
			Handler:    _VersionHistoryService_GatAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _VersionHistoryService_Update_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _VersionHistoryService_GetByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "version_history.proto",
}
