// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: billing_service.proto

package company_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_CreateFare_FullMethodName           = "/company_service.BillingService/CreateFare"
	BillingService_GetFare_FullMethodName              = "/company_service.BillingService/GetFare"
	BillingService_ListFares_FullMethodName            = "/company_service.BillingService/ListFares"
	BillingService_UpdateFare_FullMethodName           = "/company_service.BillingService/UpdateFare"
	BillingService_DeleteFare_FullMethodName           = "/company_service.BillingService/DeleteFare"
	BillingService_CalculatePrice_FullMethodName       = "/company_service.BillingService/CalculatePrice"
	BillingService_CreateFareItem_FullMethodName       = "/company_service.BillingService/CreateFareItem"
	BillingService_GetFareItem_FullMethodName          = "/company_service.BillingService/GetFareItem"
	BillingService_ListFareItems_FullMethodName        = "/company_service.BillingService/ListFareItems"
	BillingService_UpdateFareItem_FullMethodName       = "/company_service.BillingService/UpdateFareItem"
	BillingService_DeleteFareItem_FullMethodName       = "/company_service.BillingService/DeleteFareItem"
	BillingService_CreateTransaction_FullMethodName    = "/company_service.BillingService/CreateTransaction"
	BillingService_GetTransaction_FullMethodName       = "/company_service.BillingService/GetTransaction"
	BillingService_ListTransactions_FullMethodName     = "/company_service.BillingService/ListTransactions"
	BillingService_UpdateTransaction_FullMethodName    = "/company_service.BillingService/UpdateTransaction"
	BillingService_CompareFunction_FullMethodName      = "/company_service.BillingService/CompareFunction"
	BillingService_UpsertMonthlyRequest_FullMethodName = "/company_service.BillingService/UpsertMonthlyRequest"
	BillingService_CreateCard_FullMethodName           = "/company_service.BillingService/CreateCard"
	BillingService_GetProjectCard_FullMethodName       = "/company_service.BillingService/GetProjectCard"
	BillingService_GetVerifyCode_FullMethodName        = "/company_service.BillingService/GetVerifyCode"
	BillingService_Verify_FullMethodName               = "/company_service.BillingService/Verify"
	BillingService_UpdateProjectCard_FullMethodName    = "/company_service.BillingService/UpdateProjectCard"
	BillingService_ListProjectCards_FullMethodName     = "/company_service.BillingService/ListProjectCards"
	BillingService_ReceiptPay_FullMethodName           = "/company_service.BillingService/ReceiptPay"
	BillingService_DeleteProjectCard_FullMethodName    = "/company_service.BillingService/DeleteProjectCard"
	BillingService_GetSubscription_FullMethodName      = "/company_service.BillingService/GetSubscription"
	BillingService_UpdateSubscription_FullMethodName   = "/company_service.BillingService/UpdateSubscription"
	BillingService_ListDiscounts_FullMethodName        = "/company_service.BillingService/ListDiscounts"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingServiceClient interface {
	// Fare Methods
	CreateFare(ctx context.Context, in *CreateFareRequest, opts ...grpc.CallOption) (*Fare, error)
	GetFare(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Fare, error)
	ListFares(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListFareResponse, error)
	UpdateFare(ctx context.Context, in *Fare, opts ...grpc.CallOption) (*Fare, error)
	DeleteFare(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
	CalculatePrice(ctx context.Context, in *CalculatePriceRequest, opts ...grpc.CallOption) (*CalculatePriceResponse, error)
	// Fare Item Methods
	CreateFareItem(ctx context.Context, in *CreateFareItemRequest, opts ...grpc.CallOption) (*FareItem, error)
	GetFareItem(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*FareItem, error)
	ListFareItems(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListFareItemsResponse, error)
	UpdateFareItem(ctx context.Context, in *FareItem, opts ...grpc.CallOption) (*FareItem, error)
	DeleteFareItem(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
	// Transaction Methods
	CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	GetTransaction(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Transaction, error)
	ListTransactions(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	UpdateTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Transaction, error)
	// Compare
	CompareFunction(ctx context.Context, in *CompareFunctionRequest, opts ...grpc.CallOption) (*CompareFunctionResponse, error)
	UpsertMonthlyRequest(ctx context.Context, in *MonthlyRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Payme
	CreateCard(ctx context.Context, in *CreateProjectCardRequest, opts ...grpc.CallOption) (*ProjectCard, error)
	GetProjectCard(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*ProjectCard, error)
	GetVerifyCode(ctx context.Context, in *GetVerifyCodeRequest, opts ...grpc.CallOption) (*GetVerifyCodeResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*ProjectCard, error)
	UpdateProjectCard(ctx context.Context, in *ProjectCard, opts ...grpc.CallOption) (*ProjectCard, error)
	ListProjectCards(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListProjectCardsResponse, error)
	ReceiptPay(ctx context.Context, in *ReceiptPayRequest, opts ...grpc.CallOption) (*ReceiptPayResponse, error)
	DeleteProjectCard(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
	// Subscription
	GetSubscription(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Subscription, error)
	UpdateSubscription(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Subscription, error)
	// Discount
	ListDiscounts(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListDiscountsResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) CreateFare(ctx context.Context, in *CreateFareRequest, opts ...grpc.CallOption) (*Fare, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fare)
	err := c.cc.Invoke(ctx, BillingService_CreateFare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetFare(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Fare, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fare)
	err := c.cc.Invoke(ctx, BillingService_GetFare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListFares(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListFareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFareResponse)
	err := c.cc.Invoke(ctx, BillingService_ListFares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) UpdateFare(ctx context.Context, in *Fare, opts ...grpc.CallOption) (*Fare, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fare)
	err := c.cc.Invoke(ctx, BillingService_UpdateFare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) DeleteFare(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, BillingService_DeleteFare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CalculatePrice(ctx context.Context, in *CalculatePriceRequest, opts ...grpc.CallOption) (*CalculatePriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculatePriceResponse)
	err := c.cc.Invoke(ctx, BillingService_CalculatePrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CreateFareItem(ctx context.Context, in *CreateFareItemRequest, opts ...grpc.CallOption) (*FareItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FareItem)
	err := c.cc.Invoke(ctx, BillingService_CreateFareItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetFareItem(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*FareItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FareItem)
	err := c.cc.Invoke(ctx, BillingService_GetFareItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListFareItems(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListFareItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFareItemsResponse)
	err := c.cc.Invoke(ctx, BillingService_ListFareItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) UpdateFareItem(ctx context.Context, in *FareItem, opts ...grpc.CallOption) (*FareItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FareItem)
	err := c.cc.Invoke(ctx, BillingService_UpdateFareItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) DeleteFareItem(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, BillingService_DeleteFareItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, BillingService_CreateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetTransaction(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, BillingService_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListTransactions(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, BillingService_ListTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) UpdateTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, BillingService_UpdateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CompareFunction(ctx context.Context, in *CompareFunctionRequest, opts ...grpc.CallOption) (*CompareFunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareFunctionResponse)
	err := c.cc.Invoke(ctx, BillingService_CompareFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) UpsertMonthlyRequest(ctx context.Context, in *MonthlyRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, BillingService_UpsertMonthlyRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CreateCard(ctx context.Context, in *CreateProjectCardRequest, opts ...grpc.CallOption) (*ProjectCard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectCard)
	err := c.cc.Invoke(ctx, BillingService_CreateCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetProjectCard(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*ProjectCard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectCard)
	err := c.cc.Invoke(ctx, BillingService_GetProjectCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetVerifyCode(ctx context.Context, in *GetVerifyCodeRequest, opts ...grpc.CallOption) (*GetVerifyCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVerifyCodeResponse)
	err := c.cc.Invoke(ctx, BillingService_GetVerifyCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*ProjectCard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectCard)
	err := c.cc.Invoke(ctx, BillingService_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) UpdateProjectCard(ctx context.Context, in *ProjectCard, opts ...grpc.CallOption) (*ProjectCard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectCard)
	err := c.cc.Invoke(ctx, BillingService_UpdateProjectCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListProjectCards(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListProjectCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectCardsResponse)
	err := c.cc.Invoke(ctx, BillingService_ListProjectCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ReceiptPay(ctx context.Context, in *ReceiptPayRequest, opts ...grpc.CallOption) (*ReceiptPayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiptPayResponse)
	err := c.cc.Invoke(ctx, BillingService_ReceiptPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) DeleteProjectCard(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, BillingService_DeleteProjectCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetSubscription(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Subscription, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Subscription)
	err := c.cc.Invoke(ctx, BillingService_GetSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) UpdateSubscription(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Subscription, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Subscription)
	err := c.cc.Invoke(ctx, BillingService_UpdateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListDiscounts(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListDiscountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiscountsResponse)
	err := c.cc.Invoke(ctx, BillingService_ListDiscounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
type BillingServiceServer interface {
	// Fare Methods
	CreateFare(context.Context, *CreateFareRequest) (*Fare, error)
	GetFare(context.Context, *PrimaryKey) (*Fare, error)
	ListFares(context.Context, *ListRequest) (*ListFareResponse, error)
	UpdateFare(context.Context, *Fare) (*Fare, error)
	DeleteFare(context.Context, *PrimaryKey) (*empty.Empty, error)
	CalculatePrice(context.Context, *CalculatePriceRequest) (*CalculatePriceResponse, error)
	// Fare Item Methods
	CreateFareItem(context.Context, *CreateFareItemRequest) (*FareItem, error)
	GetFareItem(context.Context, *PrimaryKey) (*FareItem, error)
	ListFareItems(context.Context, *ListRequest) (*ListFareItemsResponse, error)
	UpdateFareItem(context.Context, *FareItem) (*FareItem, error)
	DeleteFareItem(context.Context, *PrimaryKey) (*empty.Empty, error)
	// Transaction Methods
	CreateTransaction(context.Context, *CreateTransactionRequest) (*Transaction, error)
	GetTransaction(context.Context, *PrimaryKey) (*Transaction, error)
	ListTransactions(context.Context, *ListRequest) (*ListTransactionsResponse, error)
	UpdateTransaction(context.Context, *Transaction) (*Transaction, error)
	// Compare
	CompareFunction(context.Context, *CompareFunctionRequest) (*CompareFunctionResponse, error)
	UpsertMonthlyRequest(context.Context, *MonthlyRequest) (*empty.Empty, error)
	// Payme
	CreateCard(context.Context, *CreateProjectCardRequest) (*ProjectCard, error)
	GetProjectCard(context.Context, *PrimaryKey) (*ProjectCard, error)
	GetVerifyCode(context.Context, *GetVerifyCodeRequest) (*GetVerifyCodeResponse, error)
	Verify(context.Context, *VerifyRequest) (*ProjectCard, error)
	UpdateProjectCard(context.Context, *ProjectCard) (*ProjectCard, error)
	ListProjectCards(context.Context, *ListRequest) (*ListProjectCardsResponse, error)
	ReceiptPay(context.Context, *ReceiptPayRequest) (*ReceiptPayResponse, error)
	DeleteProjectCard(context.Context, *PrimaryKey) (*empty.Empty, error)
	// Subscription
	GetSubscription(context.Context, *PrimaryKey) (*Subscription, error)
	UpdateSubscription(context.Context, *Subscription) (*Subscription, error)
	// Discount
	ListDiscounts(context.Context, *ListRequest) (*ListDiscountsResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) CreateFare(context.Context, *CreateFareRequest) (*Fare, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFare not implemented")
}
func (UnimplementedBillingServiceServer) GetFare(context.Context, *PrimaryKey) (*Fare, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFare not implemented")
}
func (UnimplementedBillingServiceServer) ListFares(context.Context, *ListRequest) (*ListFareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFares not implemented")
}
func (UnimplementedBillingServiceServer) UpdateFare(context.Context, *Fare) (*Fare, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFare not implemented")
}
func (UnimplementedBillingServiceServer) DeleteFare(context.Context, *PrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFare not implemented")
}
func (UnimplementedBillingServiceServer) CalculatePrice(context.Context, *CalculatePriceRequest) (*CalculatePriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculatePrice not implemented")
}
func (UnimplementedBillingServiceServer) CreateFareItem(context.Context, *CreateFareItemRequest) (*FareItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFareItem not implemented")
}
func (UnimplementedBillingServiceServer) GetFareItem(context.Context, *PrimaryKey) (*FareItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFareItem not implemented")
}
func (UnimplementedBillingServiceServer) ListFareItems(context.Context, *ListRequest) (*ListFareItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFareItems not implemented")
}
func (UnimplementedBillingServiceServer) UpdateFareItem(context.Context, *FareItem) (*FareItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFareItem not implemented")
}
func (UnimplementedBillingServiceServer) DeleteFareItem(context.Context, *PrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFareItem not implemented")
}
func (UnimplementedBillingServiceServer) CreateTransaction(context.Context, *CreateTransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (UnimplementedBillingServiceServer) GetTransaction(context.Context, *PrimaryKey) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedBillingServiceServer) ListTransactions(context.Context, *ListRequest) (*ListTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedBillingServiceServer) UpdateTransaction(context.Context, *Transaction) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTransaction not implemented")
}
func (UnimplementedBillingServiceServer) CompareFunction(context.Context, *CompareFunctionRequest) (*CompareFunctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompareFunction not implemented")
}
func (UnimplementedBillingServiceServer) UpsertMonthlyRequest(context.Context, *MonthlyRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertMonthlyRequest not implemented")
}
func (UnimplementedBillingServiceServer) CreateCard(context.Context, *CreateProjectCardRequest) (*ProjectCard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCard not implemented")
}
func (UnimplementedBillingServiceServer) GetProjectCard(context.Context, *PrimaryKey) (*ProjectCard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectCard not implemented")
}
func (UnimplementedBillingServiceServer) GetVerifyCode(context.Context, *GetVerifyCodeRequest) (*GetVerifyCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerifyCode not implemented")
}
func (UnimplementedBillingServiceServer) Verify(context.Context, *VerifyRequest) (*ProjectCard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedBillingServiceServer) UpdateProjectCard(context.Context, *ProjectCard) (*ProjectCard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectCard not implemented")
}
func (UnimplementedBillingServiceServer) ListProjectCards(context.Context, *ListRequest) (*ListProjectCardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjectCards not implemented")
}
func (UnimplementedBillingServiceServer) ReceiptPay(context.Context, *ReceiptPayRequest) (*ReceiptPayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiptPay not implemented")
}
func (UnimplementedBillingServiceServer) DeleteProjectCard(context.Context, *PrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProjectCard not implemented")
}
func (UnimplementedBillingServiceServer) GetSubscription(context.Context, *PrimaryKey) (*Subscription, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedBillingServiceServer) UpdateSubscription(context.Context, *Subscription) (*Subscription, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubscription not implemented")
}
func (UnimplementedBillingServiceServer) ListDiscounts(context.Context, *ListRequest) (*ListDiscountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDiscounts not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call pancis, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_CreateFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreateFare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateFare(ctx, req.(*CreateFareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetFare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetFare(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListFares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListFares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListFares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListFares(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_UpdateFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Fare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).UpdateFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_UpdateFare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).UpdateFare(ctx, req.(*Fare))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_DeleteFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).DeleteFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_DeleteFare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).DeleteFare(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CalculatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CalculatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CalculatePrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CalculatePrice(ctx, req.(*CalculatePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CreateFareItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFareItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateFareItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreateFareItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateFareItem(ctx, req.(*CreateFareItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetFareItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetFareItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetFareItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetFareItem(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListFareItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListFareItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListFareItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListFareItems(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_UpdateFareItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FareItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).UpdateFareItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_UpdateFareItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).UpdateFareItem(ctx, req.(*FareItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_DeleteFareItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).DeleteFareItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_DeleteFareItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).DeleteFareItem(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetTransaction(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListTransactions(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_UpdateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).UpdateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_UpdateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).UpdateTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CompareFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CompareFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CompareFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CompareFunction(ctx, req.(*CompareFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_UpsertMonthlyRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonthlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).UpsertMonthlyRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_UpsertMonthlyRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).UpsertMonthlyRequest(ctx, req.(*MonthlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CreateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateCard(ctx, req.(*CreateProjectCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetProjectCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetProjectCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetProjectCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetProjectCard(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetVerifyCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetVerifyCode(ctx, req.(*GetVerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_UpdateProjectCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectCard)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).UpdateProjectCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_UpdateProjectCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).UpdateProjectCard(ctx, req.(*ProjectCard))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListProjectCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListProjectCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListProjectCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListProjectCards(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ReceiptPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiptPayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ReceiptPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ReceiptPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ReceiptPay(ctx, req.(*ReceiptPayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_DeleteProjectCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).DeleteProjectCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_DeleteProjectCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).DeleteProjectCard(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetSubscription(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_UpdateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).UpdateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_UpdateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).UpdateSubscription(ctx, req.(*Subscription))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListDiscounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListDiscounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListDiscounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListDiscounts(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "company_service.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFare",
			Handler:    _BillingService_CreateFare_Handler,
		},
		{
			MethodName: "GetFare",
			Handler:    _BillingService_GetFare_Handler,
		},
		{
			MethodName: "ListFares",
			Handler:    _BillingService_ListFares_Handler,
		},
		{
			MethodName: "UpdateFare",
			Handler:    _BillingService_UpdateFare_Handler,
		},
		{
			MethodName: "DeleteFare",
			Handler:    _BillingService_DeleteFare_Handler,
		},
		{
			MethodName: "CalculatePrice",
			Handler:    _BillingService_CalculatePrice_Handler,
		},
		{
			MethodName: "CreateFareItem",
			Handler:    _BillingService_CreateFareItem_Handler,
		},
		{
			MethodName: "GetFareItem",
			Handler:    _BillingService_GetFareItem_Handler,
		},
		{
			MethodName: "ListFareItems",
			Handler:    _BillingService_ListFareItems_Handler,
		},
		{
			MethodName: "UpdateFareItem",
			Handler:    _BillingService_UpdateFareItem_Handler,
		},
		{
			MethodName: "DeleteFareItem",
			Handler:    _BillingService_DeleteFareItem_Handler,
		},
		{
			MethodName: "CreateTransaction",
			Handler:    _BillingService_CreateTransaction_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _BillingService_GetTransaction_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _BillingService_ListTransactions_Handler,
		},
		{
			MethodName: "UpdateTransaction",
			Handler:    _BillingService_UpdateTransaction_Handler,
		},
		{
			MethodName: "CompareFunction",
			Handler:    _BillingService_CompareFunction_Handler,
		},
		{
			MethodName: "UpsertMonthlyRequest",
			Handler:    _BillingService_UpsertMonthlyRequest_Handler,
		},
		{
			MethodName: "CreateCard",
			Handler:    _BillingService_CreateCard_Handler,
		},
		{
			MethodName: "GetProjectCard",
			Handler:    _BillingService_GetProjectCard_Handler,
		},
		{
			MethodName: "GetVerifyCode",
			Handler:    _BillingService_GetVerifyCode_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _BillingService_Verify_Handler,
		},
		{
			MethodName: "UpdateProjectCard",
			Handler:    _BillingService_UpdateProjectCard_Handler,
		},
		{
			MethodName: "ListProjectCards",
			Handler:    _BillingService_ListProjectCards_Handler,
		},
		{
			MethodName: "ReceiptPay",
			Handler:    _BillingService_ReceiptPay_Handler,
		},
		{
			MethodName: "DeleteProjectCard",
			Handler:    _BillingService_DeleteProjectCard_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _BillingService_GetSubscription_Handler,
		},
		{
			MethodName: "UpdateSubscription",
			Handler:    _BillingService_UpdateSubscription_Handler,
		},
		{
			MethodName: "ListDiscounts",
			Handler:    _BillingService_ListDiscounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing_service.proto",
}
