// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: integration_resource_service.proto

package company_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntegrationResourceService_CreateIntegrationResource_FullMethodName  = "/company_service.IntegrationResourceService/CreateIntegrationResource"
	IntegrationResourceService_GetById_FullMethodName                    = "/company_service.IntegrationResourceService/GetById"
	IntegrationResourceService_GetByUsername_FullMethodName              = "/company_service.IntegrationResourceService/GetByUsername"
	IntegrationResourceService_GetIntegrationResourceList_FullMethodName = "/company_service.IntegrationResourceService/GetIntegrationResourceList"
	IntegrationResourceService_UpdateIntegrationResource_FullMethodName  = "/company_service.IntegrationResourceService/UpdateIntegrationResource"
	IntegrationResourceService_DeleteIntegrationResource_FullMethodName  = "/company_service.IntegrationResourceService/DeleteIntegrationResource"
)

// IntegrationResourceServiceClient is the client API for IntegrationResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntegrationResourceServiceClient interface {
	CreateIntegrationResource(ctx context.Context, in *CreateIntegrationResourceRequest, opts ...grpc.CallOption) (*IntegrationResource, error)
	GetById(ctx context.Context, in *IntegrationResourcePrimaryKey, opts ...grpc.CallOption) (*IntegrationResource, error)
	GetByUsername(ctx context.Context, in *GetByUsernameRequest, opts ...grpc.CallOption) (*GetByUsernameResponse, error)
	GetIntegrationResourceList(ctx context.Context, in *GetListIntegrationResourceRequest, opts ...grpc.CallOption) (*GetListIntegrationResourceResponse, error)
	UpdateIntegrationResource(ctx context.Context, in *UpdateIntegrationResourceRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteIntegrationResource(ctx context.Context, in *IntegrationResourcePrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
}

type integrationResourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegrationResourceServiceClient(cc grpc.ClientConnInterface) IntegrationResourceServiceClient {
	return &integrationResourceServiceClient{cc}
}

func (c *integrationResourceServiceClient) CreateIntegrationResource(ctx context.Context, in *CreateIntegrationResourceRequest, opts ...grpc.CallOption) (*IntegrationResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntegrationResource)
	err := c.cc.Invoke(ctx, IntegrationResourceService_CreateIntegrationResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationResourceServiceClient) GetById(ctx context.Context, in *IntegrationResourcePrimaryKey, opts ...grpc.CallOption) (*IntegrationResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntegrationResource)
	err := c.cc.Invoke(ctx, IntegrationResourceService_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationResourceServiceClient) GetByUsername(ctx context.Context, in *GetByUsernameRequest, opts ...grpc.CallOption) (*GetByUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByUsernameResponse)
	err := c.cc.Invoke(ctx, IntegrationResourceService_GetByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationResourceServiceClient) GetIntegrationResourceList(ctx context.Context, in *GetListIntegrationResourceRequest, opts ...grpc.CallOption) (*GetListIntegrationResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListIntegrationResourceResponse)
	err := c.cc.Invoke(ctx, IntegrationResourceService_GetIntegrationResourceList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationResourceServiceClient) UpdateIntegrationResource(ctx context.Context, in *UpdateIntegrationResourceRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, IntegrationResourceService_UpdateIntegrationResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationResourceServiceClient) DeleteIntegrationResource(ctx context.Context, in *IntegrationResourcePrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, IntegrationResourceService_DeleteIntegrationResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationResourceServiceServer is the server API for IntegrationResourceService service.
// All implementations must embed UnimplementedIntegrationResourceServiceServer
// for forward compatibility.
type IntegrationResourceServiceServer interface {
	CreateIntegrationResource(context.Context, *CreateIntegrationResourceRequest) (*IntegrationResource, error)
	GetById(context.Context, *IntegrationResourcePrimaryKey) (*IntegrationResource, error)
	GetByUsername(context.Context, *GetByUsernameRequest) (*GetByUsernameResponse, error)
	GetIntegrationResourceList(context.Context, *GetListIntegrationResourceRequest) (*GetListIntegrationResourceResponse, error)
	UpdateIntegrationResource(context.Context, *UpdateIntegrationResourceRequest) (*empty.Empty, error)
	DeleteIntegrationResource(context.Context, *IntegrationResourcePrimaryKey) (*empty.Empty, error)
	mustEmbedUnimplementedIntegrationResourceServiceServer()
}

// UnimplementedIntegrationResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntegrationResourceServiceServer struct{}

func (UnimplementedIntegrationResourceServiceServer) CreateIntegrationResource(context.Context, *CreateIntegrationResourceRequest) (*IntegrationResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIntegrationResource not implemented")
}
func (UnimplementedIntegrationResourceServiceServer) GetById(context.Context, *IntegrationResourcePrimaryKey) (*IntegrationResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedIntegrationResourceServiceServer) GetByUsername(context.Context, *GetByUsernameRequest) (*GetByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUsername not implemented")
}
func (UnimplementedIntegrationResourceServiceServer) GetIntegrationResourceList(context.Context, *GetListIntegrationResourceRequest) (*GetListIntegrationResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntegrationResourceList not implemented")
}
func (UnimplementedIntegrationResourceServiceServer) UpdateIntegrationResource(context.Context, *UpdateIntegrationResourceRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIntegrationResource not implemented")
}
func (UnimplementedIntegrationResourceServiceServer) DeleteIntegrationResource(context.Context, *IntegrationResourcePrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIntegrationResource not implemented")
}
func (UnimplementedIntegrationResourceServiceServer) mustEmbedUnimplementedIntegrationResourceServiceServer() {
}
func (UnimplementedIntegrationResourceServiceServer) testEmbeddedByValue() {}

// UnsafeIntegrationResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegrationResourceServiceServer will
// result in compilation errors.
type UnsafeIntegrationResourceServiceServer interface {
	mustEmbedUnimplementedIntegrationResourceServiceServer()
}

func RegisterIntegrationResourceServiceServer(s grpc.ServiceRegistrar, srv IntegrationResourceServiceServer) {
	// If the following call pancis, it indicates UnimplementedIntegrationResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntegrationResourceService_ServiceDesc, srv)
}

func _IntegrationResourceService_CreateIntegrationResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIntegrationResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationResourceServiceServer).CreateIntegrationResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationResourceService_CreateIntegrationResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationResourceServiceServer).CreateIntegrationResource(ctx, req.(*CreateIntegrationResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationResourceService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrationResourcePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationResourceServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationResourceService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationResourceServiceServer).GetById(ctx, req.(*IntegrationResourcePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationResourceService_GetByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationResourceServiceServer).GetByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationResourceService_GetByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationResourceServiceServer).GetByUsername(ctx, req.(*GetByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationResourceService_GetIntegrationResourceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListIntegrationResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationResourceServiceServer).GetIntegrationResourceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationResourceService_GetIntegrationResourceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationResourceServiceServer).GetIntegrationResourceList(ctx, req.(*GetListIntegrationResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationResourceService_UpdateIntegrationResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIntegrationResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationResourceServiceServer).UpdateIntegrationResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationResourceService_UpdateIntegrationResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationResourceServiceServer).UpdateIntegrationResource(ctx, req.(*UpdateIntegrationResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationResourceService_DeleteIntegrationResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrationResourcePrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationResourceServiceServer).DeleteIntegrationResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationResourceService_DeleteIntegrationResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationResourceServiceServer).DeleteIntegrationResource(ctx, req.(*IntegrationResourcePrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// IntegrationResourceService_ServiceDesc is the grpc.ServiceDesc for IntegrationResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntegrationResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "company_service.IntegrationResourceService",
	HandlerType: (*IntegrationResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIntegrationResource",
			Handler:    _IntegrationResourceService_CreateIntegrationResource_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _IntegrationResourceService_GetById_Handler,
		},
		{
			MethodName: "GetByUsername",
			Handler:    _IntegrationResourceService_GetByUsername_Handler,
		},
		{
			MethodName: "GetIntegrationResourceList",
			Handler:    _IntegrationResourceService_GetIntegrationResourceList_Handler,
		},
		{
			MethodName: "UpdateIntegrationResource",
			Handler:    _IntegrationResourceService_UpdateIntegrationResource_Handler,
		},
		{
			MethodName: "DeleteIntegrationResource",
			Handler:    _IntegrationResourceService_DeleteIntegrationResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integration_resource_service.proto",
}
