// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: projects_service.proto

package company_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectService_Create_FullMethodName                       = "/company_service.ProjectService/Create"
	ProjectService_GetList_FullMethodName                      = "/company_service.ProjectService/GetList"
	ProjectService_GetById_FullMethodName                      = "/company_service.ProjectService/GetById"
	ProjectService_Update_FullMethodName                       = "/company_service.ProjectService/Update"
	ProjectService_Delete_FullMethodName                       = "/company_service.ProjectService/Delete"
	ProjectService_GetProjects_FullMethodName                  = "/company_service.ProjectService/GetProjects"
	ProjectService_GetProjectsByCompanyId_FullMethodName       = "/company_service.ProjectService/GetProjectsByCompanyId"
	ProjectService_UpdateProjectUserData_FullMethodName        = "/company_service.ProjectService/UpdateProjectUserData"
	ProjectService_GetListSetting_FullMethodName               = "/company_service.ProjectService/GetListSetting"
	ProjectService_AttachFare_FullMethodName                   = "/company_service.ProjectService/AttachFare"
	ProjectService_CreateProjectLoginMicroFront_FullMethodName = "/company_service.ProjectService/CreateProjectLoginMicroFront"
	ProjectService_GetProjectLoginMicroFront_FullMethodName    = "/company_service.ProjectService/GetProjectLoginMicroFront"
	ProjectService_UpdateProjectLoginMicroFront_FullMethodName = "/company_service.ProjectService/UpdateProjectLoginMicroFront"
	ProjectService_UpdateProjectConfig_FullMethodName          = "/company_service.ProjectService/UpdateProjectConfig"
	ProjectService_GetPorjectConfigByProjectId_FullMethodName  = "/company_service.ProjectService/GetPorjectConfigByProjectId"
	ProjectService_GetProjectConfigList_FullMethodName         = "/company_service.ProjectService/GetProjectConfigList"
	ProjectService_UpsertRecord_FullMethodName                 = "/company_service.ProjectService/UpsertRecord"
	ProjectService_ListRecord_FullMethodName                   = "/company_service.ProjectService/ListRecord"
	ProjectService_ListProjectsRPS_FullMethodName              = "/company_service.ProjectService/ListProjectsRPS"
)

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectServiceClient interface {
	Create(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	GetList(ctx context.Context, in *GetProjectListRequest, opts ...grpc.CallOption) (*GetProjectListResponse, error)
	GetById(ctx context.Context, in *GetProjectByIdRequest, opts ...grpc.CallOption) (*Project, error)
	Update(ctx context.Context, in *Project, opts ...grpc.CallOption) (*Project, error)
	Delete(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*EmptyProto, error)
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error)
	GetProjectsByCompanyId(ctx context.Context, in *GetProjectsByCompanyIdReq, opts ...grpc.CallOption) (*GetProjectsByCompanyIdRes, error)
	UpdateProjectUserData(ctx context.Context, in *UpdateProjectUserDataReq, opts ...grpc.CallOption) (*UpdateProjectUserDataRes, error)
	GetListSetting(ctx context.Context, in *GetListSettingReq, opts ...grpc.CallOption) (*Setting, error)
	AttachFare(ctx context.Context, in *AttachFareRequest, opts ...grpc.CallOption) (*Project, error)
	CreateProjectLoginMicroFront(ctx context.Context, in *ProjectLoginMicroFrontend, opts ...grpc.CallOption) (*ProjectLoginMicroFrontend, error)
	GetProjectLoginMicroFront(ctx context.Context, in *GetProjectLoginMicroFrontRequest, opts ...grpc.CallOption) (*ProjectLoginMicroFrontend, error)
	UpdateProjectLoginMicroFront(ctx context.Context, in *ProjectLoginMicroFrontend, opts ...grpc.CallOption) (*ProjectLoginMicroFrontend, error)
	UpdateProjectConfig(ctx context.Context, in *ProjectConfig, opts ...grpc.CallOption) (*ProjectConfig, error)
	GetPorjectConfigByProjectId(ctx context.Context, in *GetPorjectConfigByProjectIdRequest, opts ...grpc.CallOption) (*ProjectConfig, error)
	GetProjectConfigList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListPorjectConfig, error)
	UpsertRecord(ctx context.Context, in *Record, opts ...grpc.CallOption) (*EmptyProto, error)
	ListRecord(ctx context.Context, in *ListRecordRequest, opts ...grpc.CallOption) (*EmptyProto, error)
	ListProjectsRPS(ctx context.Context, in *GetProjectListRequest, opts ...grpc.CallOption) (*ListProjectsRPSResponse, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) Create(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, ProjectService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetList(ctx context.Context, in *GetProjectListRequest, opts ...grpc.CallOption) (*GetProjectListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectListResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetById(ctx context.Context, in *GetProjectByIdRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, ProjectService_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Update(ctx context.Context, in *Project, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, ProjectService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Delete(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*EmptyProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyProto)
	err := c.cc.Invoke(ctx, ProjectService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectsResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectsByCompanyId(ctx context.Context, in *GetProjectsByCompanyIdReq, opts ...grpc.CallOption) (*GetProjectsByCompanyIdRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectsByCompanyIdRes)
	err := c.cc.Invoke(ctx, ProjectService_GetProjectsByCompanyId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProjectUserData(ctx context.Context, in *UpdateProjectUserDataReq, opts ...grpc.CallOption) (*UpdateProjectUserDataRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProjectUserDataRes)
	err := c.cc.Invoke(ctx, ProjectService_UpdateProjectUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetListSetting(ctx context.Context, in *GetListSettingReq, opts ...grpc.CallOption) (*Setting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Setting)
	err := c.cc.Invoke(ctx, ProjectService_GetListSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) AttachFare(ctx context.Context, in *AttachFareRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, ProjectService_AttachFare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) CreateProjectLoginMicroFront(ctx context.Context, in *ProjectLoginMicroFrontend, opts ...grpc.CallOption) (*ProjectLoginMicroFrontend, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectLoginMicroFrontend)
	err := c.cc.Invoke(ctx, ProjectService_CreateProjectLoginMicroFront_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectLoginMicroFront(ctx context.Context, in *GetProjectLoginMicroFrontRequest, opts ...grpc.CallOption) (*ProjectLoginMicroFrontend, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectLoginMicroFrontend)
	err := c.cc.Invoke(ctx, ProjectService_GetProjectLoginMicroFront_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProjectLoginMicroFront(ctx context.Context, in *ProjectLoginMicroFrontend, opts ...grpc.CallOption) (*ProjectLoginMicroFrontend, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectLoginMicroFrontend)
	err := c.cc.Invoke(ctx, ProjectService_UpdateProjectLoginMicroFront_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProjectConfig(ctx context.Context, in *ProjectConfig, opts ...grpc.CallOption) (*ProjectConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectConfig)
	err := c.cc.Invoke(ctx, ProjectService_UpdateProjectConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetPorjectConfigByProjectId(ctx context.Context, in *GetPorjectConfigByProjectIdRequest, opts ...grpc.CallOption) (*ProjectConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectConfig)
	err := c.cc.Invoke(ctx, ProjectService_GetPorjectConfigByProjectId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectConfigList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListPorjectConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPorjectConfig)
	err := c.cc.Invoke(ctx, ProjectService_GetProjectConfigList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpsertRecord(ctx context.Context, in *Record, opts ...grpc.CallOption) (*EmptyProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyProto)
	err := c.cc.Invoke(ctx, ProjectService_UpsertRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListRecord(ctx context.Context, in *ListRecordRequest, opts ...grpc.CallOption) (*EmptyProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyProto)
	err := c.cc.Invoke(ctx, ProjectService_ListRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListProjectsRPS(ctx context.Context, in *GetProjectListRequest, opts ...grpc.CallOption) (*ListProjectsRPSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsRPSResponse)
	err := c.cc.Invoke(ctx, ProjectService_ListProjectsRPS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations must embed UnimplementedProjectServiceServer
// for forward compatibility.
type ProjectServiceServer interface {
	Create(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	GetList(context.Context, *GetProjectListRequest) (*GetProjectListResponse, error)
	GetById(context.Context, *GetProjectByIdRequest) (*Project, error)
	Update(context.Context, *Project) (*Project, error)
	Delete(context.Context, *DeleteProjectRequest) (*EmptyProto, error)
	GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error)
	GetProjectsByCompanyId(context.Context, *GetProjectsByCompanyIdReq) (*GetProjectsByCompanyIdRes, error)
	UpdateProjectUserData(context.Context, *UpdateProjectUserDataReq) (*UpdateProjectUserDataRes, error)
	GetListSetting(context.Context, *GetListSettingReq) (*Setting, error)
	AttachFare(context.Context, *AttachFareRequest) (*Project, error)
	CreateProjectLoginMicroFront(context.Context, *ProjectLoginMicroFrontend) (*ProjectLoginMicroFrontend, error)
	GetProjectLoginMicroFront(context.Context, *GetProjectLoginMicroFrontRequest) (*ProjectLoginMicroFrontend, error)
	UpdateProjectLoginMicroFront(context.Context, *ProjectLoginMicroFrontend) (*ProjectLoginMicroFrontend, error)
	UpdateProjectConfig(context.Context, *ProjectConfig) (*ProjectConfig, error)
	GetPorjectConfigByProjectId(context.Context, *GetPorjectConfigByProjectIdRequest) (*ProjectConfig, error)
	GetProjectConfigList(context.Context, *empty.Empty) (*ListPorjectConfig, error)
	UpsertRecord(context.Context, *Record) (*EmptyProto, error)
	ListRecord(context.Context, *ListRecordRequest) (*EmptyProto, error)
	ListProjectsRPS(context.Context, *GetProjectListRequest) (*ListProjectsRPSResponse, error)
	mustEmbedUnimplementedProjectServiceServer()
}

// UnimplementedProjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectServiceServer struct{}

func (UnimplementedProjectServiceServer) Create(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProjectServiceServer) GetList(context.Context, *GetProjectListRequest) (*GetProjectListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedProjectServiceServer) GetById(context.Context, *GetProjectByIdRequest) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedProjectServiceServer) Update(context.Context, *Project) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProjectServiceServer) Delete(context.Context, *DeleteProjectRequest) (*EmptyProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProjectServiceServer) GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjects not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectsByCompanyId(context.Context, *GetProjectsByCompanyIdReq) (*GetProjectsByCompanyIdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectsByCompanyId not implemented")
}
func (UnimplementedProjectServiceServer) UpdateProjectUserData(context.Context, *UpdateProjectUserDataReq) (*UpdateProjectUserDataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectUserData not implemented")
}
func (UnimplementedProjectServiceServer) GetListSetting(context.Context, *GetListSettingReq) (*Setting, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListSetting not implemented")
}
func (UnimplementedProjectServiceServer) AttachFare(context.Context, *AttachFareRequest) (*Project, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachFare not implemented")
}
func (UnimplementedProjectServiceServer) CreateProjectLoginMicroFront(context.Context, *ProjectLoginMicroFrontend) (*ProjectLoginMicroFrontend, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProjectLoginMicroFront not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectLoginMicroFront(context.Context, *GetProjectLoginMicroFrontRequest) (*ProjectLoginMicroFrontend, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectLoginMicroFront not implemented")
}
func (UnimplementedProjectServiceServer) UpdateProjectLoginMicroFront(context.Context, *ProjectLoginMicroFrontend) (*ProjectLoginMicroFrontend, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectLoginMicroFront not implemented")
}
func (UnimplementedProjectServiceServer) UpdateProjectConfig(context.Context, *ProjectConfig) (*ProjectConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectConfig not implemented")
}
func (UnimplementedProjectServiceServer) GetPorjectConfigByProjectId(context.Context, *GetPorjectConfigByProjectIdRequest) (*ProjectConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPorjectConfigByProjectId not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectConfigList(context.Context, *empty.Empty) (*ListPorjectConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectConfigList not implemented")
}
func (UnimplementedProjectServiceServer) UpsertRecord(context.Context, *Record) (*EmptyProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertRecord not implemented")
}
func (UnimplementedProjectServiceServer) ListRecord(context.Context, *ListRecordRequest) (*EmptyProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecord not implemented")
}
func (UnimplementedProjectServiceServer) ListProjectsRPS(context.Context, *GetProjectListRequest) (*ListProjectsRPSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjectsRPS not implemented")
}
func (UnimplementedProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {}
func (UnimplementedProjectServiceServer) testEmbeddedByValue()                        {}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	// If the following call pancis, it indicates UnimplementedProjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Create(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetList(ctx, req.(*GetProjectListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetById(ctx, req.(*GetProjectByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Project)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Update(ctx, req.(*Project))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Delete(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectsByCompanyId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsByCompanyIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectsByCompanyId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjectsByCompanyId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectsByCompanyId(ctx, req.(*GetProjectsByCompanyIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProjectUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectUserDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProjectUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateProjectUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProjectUserData(ctx, req.(*UpdateProjectUserDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetListSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListSettingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetListSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetListSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetListSetting(ctx, req.(*GetListSettingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_AttachFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachFareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AttachFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_AttachFare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AttachFare(ctx, req.(*AttachFareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_CreateProjectLoginMicroFront_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectLoginMicroFrontend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CreateProjectLoginMicroFront(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_CreateProjectLoginMicroFront_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CreateProjectLoginMicroFront(ctx, req.(*ProjectLoginMicroFrontend))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectLoginMicroFront_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectLoginMicroFrontRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectLoginMicroFront(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjectLoginMicroFront_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectLoginMicroFront(ctx, req.(*GetProjectLoginMicroFrontRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProjectLoginMicroFront_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectLoginMicroFrontend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProjectLoginMicroFront(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateProjectLoginMicroFront_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProjectLoginMicroFront(ctx, req.(*ProjectLoginMicroFrontend))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProjectConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProjectConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpdateProjectConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProjectConfig(ctx, req.(*ProjectConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetPorjectConfigByProjectId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPorjectConfigByProjectIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetPorjectConfigByProjectId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetPorjectConfigByProjectId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetPorjectConfigByProjectId(ctx, req.(*GetPorjectConfigByProjectIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectConfigList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectConfigList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjectConfigList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectConfigList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpsertRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpsertRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UpsertRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpsertRecord(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ListRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListRecord(ctx, req.(*ListRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListProjectsRPS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListProjectsRPS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ListProjectsRPS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListProjectsRPS(ctx, req.(*GetProjectListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "company_service.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProjectService_Create_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _ProjectService_GetList_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _ProjectService_GetById_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProjectService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProjectService_Delete_Handler,
		},
		{
			MethodName: "GetProjects",
			Handler:    _ProjectService_GetProjects_Handler,
		},
		{
			MethodName: "GetProjectsByCompanyId",
			Handler:    _ProjectService_GetProjectsByCompanyId_Handler,
		},
		{
			MethodName: "UpdateProjectUserData",
			Handler:    _ProjectService_UpdateProjectUserData_Handler,
		},
		{
			MethodName: "GetListSetting",
			Handler:    _ProjectService_GetListSetting_Handler,
		},
		{
			MethodName: "AttachFare",
			Handler:    _ProjectService_AttachFare_Handler,
		},
		{
			MethodName: "CreateProjectLoginMicroFront",
			Handler:    _ProjectService_CreateProjectLoginMicroFront_Handler,
		},
		{
			MethodName: "GetProjectLoginMicroFront",
			Handler:    _ProjectService_GetProjectLoginMicroFront_Handler,
		},
		{
			MethodName: "UpdateProjectLoginMicroFront",
			Handler:    _ProjectService_UpdateProjectLoginMicroFront_Handler,
		},
		{
			MethodName: "UpdateProjectConfig",
			Handler:    _ProjectService_UpdateProjectConfig_Handler,
		},
		{
			MethodName: "GetPorjectConfigByProjectId",
			Handler:    _ProjectService_GetPorjectConfigByProjectId_Handler,
		},
		{
			MethodName: "GetProjectConfigList",
			Handler:    _ProjectService_GetProjectConfigList_Handler,
		},
		{
			MethodName: "UpsertRecord",
			Handler:    _ProjectService_UpsertRecord_Handler,
		},
		{
			MethodName: "ListRecord",
			Handler:    _ProjectService_ListRecord_Handler,
		},
		{
			MethodName: "ListProjectsRPS",
			Handler:    _ProjectService_ListProjectsRPS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "projects_service.proto",
}
