// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: redirect_service.proto

package company_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedirectUrlService_Create_FullMethodName      = "/company_service.RedirectUrlService/Create"
	RedirectUrlService_Update_FullMethodName      = "/company_service.RedirectUrlService/Update"
	RedirectUrlService_GetSingle_FullMethodName   = "/company_service.RedirectUrlService/GetSingle"
	RedirectUrlService_GetList_FullMethodName     = "/company_service.RedirectUrlService/GetList"
	RedirectUrlService_Delete_FullMethodName      = "/company_service.RedirectUrlService/Delete"
	RedirectUrlService_UpdateOrder_FullMethodName = "/company_service.RedirectUrlService/UpdateOrder"
)

// RedirectUrlServiceClient is the client API for RedirectUrlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedirectUrlServiceClient interface {
	Create(ctx context.Context, in *RedirectUrl, opts ...grpc.CallOption) (*RedirectUrl, error)
	Update(ctx context.Context, in *RedirectUrl, opts ...grpc.CallOption) (*RedirectUrl, error)
	GetSingle(ctx context.Context, in *GetSingleRedirectUrlReq, opts ...grpc.CallOption) (*RedirectUrl, error)
	GetList(ctx context.Context, in *GetListRedirectUrlReq, opts ...grpc.CallOption) (*GetListRedirectUrlRes, error)
	Delete(ctx context.Context, in *DeleteRedirectUrlReq, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateOrder(ctx context.Context, in *UpdateOrderRedirectUrlReq, opts ...grpc.CallOption) (*empty.Empty, error)
}

type redirectUrlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedirectUrlServiceClient(cc grpc.ClientConnInterface) RedirectUrlServiceClient {
	return &redirectUrlServiceClient{cc}
}

func (c *redirectUrlServiceClient) Create(ctx context.Context, in *RedirectUrl, opts ...grpc.CallOption) (*RedirectUrl, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedirectUrl)
	err := c.cc.Invoke(ctx, RedirectUrlService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redirectUrlServiceClient) Update(ctx context.Context, in *RedirectUrl, opts ...grpc.CallOption) (*RedirectUrl, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedirectUrl)
	err := c.cc.Invoke(ctx, RedirectUrlService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redirectUrlServiceClient) GetSingle(ctx context.Context, in *GetSingleRedirectUrlReq, opts ...grpc.CallOption) (*RedirectUrl, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedirectUrl)
	err := c.cc.Invoke(ctx, RedirectUrlService_GetSingle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redirectUrlServiceClient) GetList(ctx context.Context, in *GetListRedirectUrlReq, opts ...grpc.CallOption) (*GetListRedirectUrlRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListRedirectUrlRes)
	err := c.cc.Invoke(ctx, RedirectUrlService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redirectUrlServiceClient) Delete(ctx context.Context, in *DeleteRedirectUrlReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, RedirectUrlService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redirectUrlServiceClient) UpdateOrder(ctx context.Context, in *UpdateOrderRedirectUrlReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, RedirectUrlService_UpdateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedirectUrlServiceServer is the server API for RedirectUrlService service.
// All implementations must embed UnimplementedRedirectUrlServiceServer
// for forward compatibility.
type RedirectUrlServiceServer interface {
	Create(context.Context, *RedirectUrl) (*RedirectUrl, error)
	Update(context.Context, *RedirectUrl) (*RedirectUrl, error)
	GetSingle(context.Context, *GetSingleRedirectUrlReq) (*RedirectUrl, error)
	GetList(context.Context, *GetListRedirectUrlReq) (*GetListRedirectUrlRes, error)
	Delete(context.Context, *DeleteRedirectUrlReq) (*empty.Empty, error)
	UpdateOrder(context.Context, *UpdateOrderRedirectUrlReq) (*empty.Empty, error)
	mustEmbedUnimplementedRedirectUrlServiceServer()
}

// UnimplementedRedirectUrlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedirectUrlServiceServer struct{}

func (UnimplementedRedirectUrlServiceServer) Create(context.Context, *RedirectUrl) (*RedirectUrl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRedirectUrlServiceServer) Update(context.Context, *RedirectUrl) (*RedirectUrl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedRedirectUrlServiceServer) GetSingle(context.Context, *GetSingleRedirectUrlReq) (*RedirectUrl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingle not implemented")
}
func (UnimplementedRedirectUrlServiceServer) GetList(context.Context, *GetListRedirectUrlReq) (*GetListRedirectUrlRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedRedirectUrlServiceServer) Delete(context.Context, *DeleteRedirectUrlReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRedirectUrlServiceServer) UpdateOrder(context.Context, *UpdateOrderRedirectUrlReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (UnimplementedRedirectUrlServiceServer) mustEmbedUnimplementedRedirectUrlServiceServer() {}
func (UnimplementedRedirectUrlServiceServer) testEmbeddedByValue()                            {}

// UnsafeRedirectUrlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedirectUrlServiceServer will
// result in compilation errors.
type UnsafeRedirectUrlServiceServer interface {
	mustEmbedUnimplementedRedirectUrlServiceServer()
}

func RegisterRedirectUrlServiceServer(s grpc.ServiceRegistrar, srv RedirectUrlServiceServer) {
	// If the following call pancis, it indicates UnimplementedRedirectUrlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedirectUrlService_ServiceDesc, srv)
}

func _RedirectUrlService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedirectUrl)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedirectUrlServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedirectUrlService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedirectUrlServiceServer).Create(ctx, req.(*RedirectUrl))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedirectUrlService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedirectUrl)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedirectUrlServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedirectUrlService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedirectUrlServiceServer).Update(ctx, req.(*RedirectUrl))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedirectUrlService_GetSingle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSingleRedirectUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedirectUrlServiceServer).GetSingle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedirectUrlService_GetSingle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedirectUrlServiceServer).GetSingle(ctx, req.(*GetSingleRedirectUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedirectUrlService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRedirectUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedirectUrlServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedirectUrlService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedirectUrlServiceServer).GetList(ctx, req.(*GetListRedirectUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedirectUrlService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRedirectUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedirectUrlServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedirectUrlService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedirectUrlServiceServer).Delete(ctx, req.(*DeleteRedirectUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedirectUrlService_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRedirectUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedirectUrlServiceServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedirectUrlService_UpdateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedirectUrlServiceServer).UpdateOrder(ctx, req.(*UpdateOrderRedirectUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RedirectUrlService_ServiceDesc is the grpc.ServiceDesc for RedirectUrlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedirectUrlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "company_service.RedirectUrlService",
	HandlerType: (*RedirectUrlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _RedirectUrlService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RedirectUrlService_Update_Handler,
		},
		{
			MethodName: "GetSingle",
			Handler:    _RedirectUrlService_GetSingle_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _RedirectUrlService_GetList_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RedirectUrlService_Delete_Handler,
		},
		{
			MethodName: "UpdateOrder",
			Handler:    _RedirectUrlService_UpdateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redirect_service.proto",
}
