// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: eimzo.proto

//

package auth_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EImzoService_GetChallenge_FullMethodName         = "/auth_service.EImzoService/GetChallenge"
	EImzoService_ExtractUserFromPKCS7_FullMethodName = "/auth_service.EImzoService/ExtractUserFromPKCS7"
)

// EImzoServiceClient is the client API for EImzoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EImzoServiceClient interface {
	GetChallenge(ctx context.Context, in *GetChallengeRequest, opts ...grpc.CallOption) (*GetChallengeResponse, error)
	ExtractUserFromPKCS7(ctx context.Context, in *ExtractUserFromPKCS7Request, opts ...grpc.CallOption) (*ExtractUserFromPKCS7Response, error)
}

type eImzoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEImzoServiceClient(cc grpc.ClientConnInterface) EImzoServiceClient {
	return &eImzoServiceClient{cc}
}

func (c *eImzoServiceClient) GetChallenge(ctx context.Context, in *GetChallengeRequest, opts ...grpc.CallOption) (*GetChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChallengeResponse)
	err := c.cc.Invoke(ctx, EImzoService_GetChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eImzoServiceClient) ExtractUserFromPKCS7(ctx context.Context, in *ExtractUserFromPKCS7Request, opts ...grpc.CallOption) (*ExtractUserFromPKCS7Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractUserFromPKCS7Response)
	err := c.cc.Invoke(ctx, EImzoService_ExtractUserFromPKCS7_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EImzoServiceServer is the server API for EImzoService service.
// All implementations must embed UnimplementedEImzoServiceServer
// for forward compatibility.
type EImzoServiceServer interface {
	GetChallenge(context.Context, *GetChallengeRequest) (*GetChallengeResponse, error)
	ExtractUserFromPKCS7(context.Context, *ExtractUserFromPKCS7Request) (*ExtractUserFromPKCS7Response, error)
	mustEmbedUnimplementedEImzoServiceServer()
}

// UnimplementedEImzoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEImzoServiceServer struct{}

func (UnimplementedEImzoServiceServer) GetChallenge(context.Context, *GetChallengeRequest) (*GetChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChallenge not implemented")
}
func (UnimplementedEImzoServiceServer) ExtractUserFromPKCS7(context.Context, *ExtractUserFromPKCS7Request) (*ExtractUserFromPKCS7Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtractUserFromPKCS7 not implemented")
}
func (UnimplementedEImzoServiceServer) mustEmbedUnimplementedEImzoServiceServer() {}
func (UnimplementedEImzoServiceServer) testEmbeddedByValue()                      {}

// UnsafeEImzoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EImzoServiceServer will
// result in compilation errors.
type UnsafeEImzoServiceServer interface {
	mustEmbedUnimplementedEImzoServiceServer()
}

func RegisterEImzoServiceServer(s grpc.ServiceRegistrar, srv EImzoServiceServer) {
	// If the following call pancis, it indicates UnimplementedEImzoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EImzoService_ServiceDesc, srv)
}

func _EImzoService_GetChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EImzoServiceServer).GetChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EImzoService_GetChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EImzoServiceServer).GetChallenge(ctx, req.(*GetChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EImzoService_ExtractUserFromPKCS7_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractUserFromPKCS7Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EImzoServiceServer).ExtractUserFromPKCS7(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EImzoService_ExtractUserFromPKCS7_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EImzoServiceServer).ExtractUserFromPKCS7(ctx, req.(*ExtractUserFromPKCS7Request))
	}
	return interceptor(ctx, in, info, handler)
}

// EImzoService_ServiceDesc is the grpc.ServiceDesc for EImzoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EImzoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_service.EImzoService",
	HandlerType: (*EImzoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChallenge",
			Handler:    _EImzoService_GetChallenge_Handler,
		},
		{
			MethodName: "ExtractUserFromPKCS7",
			Handler:    _EImzoService_ExtractUserFromPKCS7_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eimzo.proto",
}
