// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: login_strategy.proto

//

package auth_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoginStrategyService_GetList_FullMethodName = "/auth_service.LoginStrategyService/GetList"
	LoginStrategyService_GetByID_FullMethodName = "/auth_service.LoginStrategyService/GetByID"
	LoginStrategyService_Upsert_FullMethodName  = "/auth_service.LoginStrategyService/Upsert"
)

// LoginStrategyServiceClient is the client API for LoginStrategyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginStrategyServiceClient interface {
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
	GetByID(ctx context.Context, in *LoginStrategyPrimaryKey, opts ...grpc.CallOption) (*LoginStrategy, error)
	Upsert(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type loginStrategyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginStrategyServiceClient(cc grpc.ClientConnInterface) LoginStrategyServiceClient {
	return &loginStrategyServiceClient{cc}
}

func (c *loginStrategyServiceClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, LoginStrategyService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginStrategyServiceClient) GetByID(ctx context.Context, in *LoginStrategyPrimaryKey, opts ...grpc.CallOption) (*LoginStrategy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginStrategy)
	err := c.cc.Invoke(ctx, LoginStrategyService_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginStrategyServiceClient) Upsert(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, LoginStrategyService_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginStrategyServiceServer is the server API for LoginStrategyService service.
// All implementations must embed UnimplementedLoginStrategyServiceServer
// for forward compatibility.
type LoginStrategyServiceServer interface {
	GetList(context.Context, *GetListRequest) (*GetListResponse, error)
	GetByID(context.Context, *LoginStrategyPrimaryKey) (*LoginStrategy, error)
	Upsert(context.Context, *UpdateRequest) (*UpdateResponse, error)
	mustEmbedUnimplementedLoginStrategyServiceServer()
}

// UnimplementedLoginStrategyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginStrategyServiceServer struct{}

func (UnimplementedLoginStrategyServiceServer) GetList(context.Context, *GetListRequest) (*GetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedLoginStrategyServiceServer) GetByID(context.Context, *LoginStrategyPrimaryKey) (*LoginStrategy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedLoginStrategyServiceServer) Upsert(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedLoginStrategyServiceServer) mustEmbedUnimplementedLoginStrategyServiceServer() {}
func (UnimplementedLoginStrategyServiceServer) testEmbeddedByValue()                              {}

// UnsafeLoginStrategyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginStrategyServiceServer will
// result in compilation errors.
type UnsafeLoginStrategyServiceServer interface {
	mustEmbedUnimplementedLoginStrategyServiceServer()
}

func RegisterLoginStrategyServiceServer(s grpc.ServiceRegistrar, srv LoginStrategyServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoginStrategyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoginStrategyService_ServiceDesc, srv)
}

func _LoginStrategyService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginStrategyServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginStrategyService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginStrategyServiceServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginStrategyService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginStrategyPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginStrategyServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginStrategyService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginStrategyServiceServer).GetByID(ctx, req.(*LoginStrategyPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginStrategyService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginStrategyServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginStrategyService_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginStrategyServiceServer).Upsert(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginStrategyService_ServiceDesc is the grpc.ServiceDesc for LoginStrategyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginStrategyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_service.LoginStrategyService",
	HandlerType: (*LoginStrategyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _LoginStrategyService_GetList_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _LoginStrategyService_GetByID_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _LoginStrategyService_Upsert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login_strategy.proto",
}
