// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: sms_otp_settings.proto

//

package auth_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmsOtpSettingsService_Create_FullMethodName  = "/auth_service.SmsOtpSettingsService/Create"
	SmsOtpSettingsService_Update_FullMethodName  = "/auth_service.SmsOtpSettingsService/Update"
	SmsOtpSettingsService_GetById_FullMethodName = "/auth_service.SmsOtpSettingsService/GetById"
	SmsOtpSettingsService_GetList_FullMethodName = "/auth_service.SmsOtpSettingsService/GetList"
	SmsOtpSettingsService_Delete_FullMethodName  = "/auth_service.SmsOtpSettingsService/Delete"
)

// SmsOtpSettingsServiceClient is the client API for SmsOtpSettingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmsOtpSettingsServiceClient interface {
	Create(ctx context.Context, in *CreateSmsOtpSettingsRequest, opts ...grpc.CallOption) (*SmsOtpSettings, error)
	Update(ctx context.Context, in *SmsOtpSettings, opts ...grpc.CallOption) (*SmsOtpSettings, error)
	GetById(ctx context.Context, in *SmsOtpSettingsPrimaryKey, opts ...grpc.CallOption) (*SmsOtpSettings, error)
	GetList(ctx context.Context, in *GetListSmsOtpSettingsRequest, opts ...grpc.CallOption) (*SmsOtpSettingsResponse, error)
	Delete(ctx context.Context, in *SmsOtpSettingsPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
}

type smsOtpSettingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmsOtpSettingsServiceClient(cc grpc.ClientConnInterface) SmsOtpSettingsServiceClient {
	return &smsOtpSettingsServiceClient{cc}
}

func (c *smsOtpSettingsServiceClient) Create(ctx context.Context, in *CreateSmsOtpSettingsRequest, opts ...grpc.CallOption) (*SmsOtpSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmsOtpSettings)
	err := c.cc.Invoke(ctx, SmsOtpSettingsService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsOtpSettingsServiceClient) Update(ctx context.Context, in *SmsOtpSettings, opts ...grpc.CallOption) (*SmsOtpSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmsOtpSettings)
	err := c.cc.Invoke(ctx, SmsOtpSettingsService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsOtpSettingsServiceClient) GetById(ctx context.Context, in *SmsOtpSettingsPrimaryKey, opts ...grpc.CallOption) (*SmsOtpSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmsOtpSettings)
	err := c.cc.Invoke(ctx, SmsOtpSettingsService_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsOtpSettingsServiceClient) GetList(ctx context.Context, in *GetListSmsOtpSettingsRequest, opts ...grpc.CallOption) (*SmsOtpSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmsOtpSettingsResponse)
	err := c.cc.Invoke(ctx, SmsOtpSettingsService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsOtpSettingsServiceClient) Delete(ctx context.Context, in *SmsOtpSettingsPrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SmsOtpSettingsService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsOtpSettingsServiceServer is the server API for SmsOtpSettingsService service.
// All implementations must embed UnimplementedSmsOtpSettingsServiceServer
// for forward compatibility.
type SmsOtpSettingsServiceServer interface {
	Create(context.Context, *CreateSmsOtpSettingsRequest) (*SmsOtpSettings, error)
	Update(context.Context, *SmsOtpSettings) (*SmsOtpSettings, error)
	GetById(context.Context, *SmsOtpSettingsPrimaryKey) (*SmsOtpSettings, error)
	GetList(context.Context, *GetListSmsOtpSettingsRequest) (*SmsOtpSettingsResponse, error)
	Delete(context.Context, *SmsOtpSettingsPrimaryKey) (*empty.Empty, error)
	mustEmbedUnimplementedSmsOtpSettingsServiceServer()
}

// UnimplementedSmsOtpSettingsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmsOtpSettingsServiceServer struct{}

func (UnimplementedSmsOtpSettingsServiceServer) Create(context.Context, *CreateSmsOtpSettingsRequest) (*SmsOtpSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSmsOtpSettingsServiceServer) Update(context.Context, *SmsOtpSettings) (*SmsOtpSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSmsOtpSettingsServiceServer) GetById(context.Context, *SmsOtpSettingsPrimaryKey) (*SmsOtpSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedSmsOtpSettingsServiceServer) GetList(context.Context, *GetListSmsOtpSettingsRequest) (*SmsOtpSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedSmsOtpSettingsServiceServer) Delete(context.Context, *SmsOtpSettingsPrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSmsOtpSettingsServiceServer) mustEmbedUnimplementedSmsOtpSettingsServiceServer() {}
func (UnimplementedSmsOtpSettingsServiceServer) testEmbeddedByValue()                               {}

// UnsafeSmsOtpSettingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmsOtpSettingsServiceServer will
// result in compilation errors.
type UnsafeSmsOtpSettingsServiceServer interface {
	mustEmbedUnimplementedSmsOtpSettingsServiceServer()
}

func RegisterSmsOtpSettingsServiceServer(s grpc.ServiceRegistrar, srv SmsOtpSettingsServiceServer) {
	// If the following call pancis, it indicates UnimplementedSmsOtpSettingsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmsOtpSettingsService_ServiceDesc, srv)
}

func _SmsOtpSettingsService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSmsOtpSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsOtpSettingsServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmsOtpSettingsService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsOtpSettingsServiceServer).Create(ctx, req.(*CreateSmsOtpSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsOtpSettingsService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsOtpSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsOtpSettingsServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmsOtpSettingsService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsOtpSettingsServiceServer).Update(ctx, req.(*SmsOtpSettings))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsOtpSettingsService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsOtpSettingsPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsOtpSettingsServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmsOtpSettingsService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsOtpSettingsServiceServer).GetById(ctx, req.(*SmsOtpSettingsPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsOtpSettingsService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListSmsOtpSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsOtpSettingsServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmsOtpSettingsService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsOtpSettingsServiceServer).GetList(ctx, req.(*GetListSmsOtpSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsOtpSettingsService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsOtpSettingsPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsOtpSettingsServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmsOtpSettingsService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsOtpSettingsServiceServer).Delete(ctx, req.(*SmsOtpSettingsPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// SmsOtpSettingsService_ServiceDesc is the grpc.ServiceDesc for SmsOtpSettingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmsOtpSettingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_service.SmsOtpSettingsService",
	HandlerType: (*SmsOtpSettingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SmsOtpSettingsService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SmsOtpSettingsService_Update_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _SmsOtpSettingsService_GetById_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _SmsOtpSettingsService_GetList_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SmsOtpSettingsService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sms_otp_settings.proto",
}
