// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: sync_user.proto

package auth_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncUserService_CreateUser_FullMethodName     = "/auth_service.SyncUserService/CreateUser"
	SyncUserService_CreateUsers_FullMethodName    = "/auth_service.SyncUserService/CreateUsers"
	SyncUserService_UpdateUser_FullMethodName     = "/auth_service.SyncUserService/UpdateUser"
	SyncUserService_DeleteUser_FullMethodName     = "/auth_service.SyncUserService/DeleteUser"
	SyncUserService_DeleteManyUser_FullMethodName = "/auth_service.SyncUserService/DeleteManyUser"
)

// SyncUserServiceClient is the client API for SyncUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncUserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateSyncUserRequest, opts ...grpc.CallOption) (*SyncUserResponse, error)
	CreateUsers(ctx context.Context, in *CreateSyncUsersRequest, opts ...grpc.CallOption) (*SyncUsersResponse, error)
	UpdateUser(ctx context.Context, in *UpdateSyncUserRequest, opts ...grpc.CallOption) (*SyncUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteSyncUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteManyUser(ctx context.Context, in *DeleteManyUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type syncUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncUserServiceClient(cc grpc.ClientConnInterface) SyncUserServiceClient {
	return &syncUserServiceClient{cc}
}

func (c *syncUserServiceClient) CreateUser(ctx context.Context, in *CreateSyncUserRequest, opts ...grpc.CallOption) (*SyncUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncUserResponse)
	err := c.cc.Invoke(ctx, SyncUserService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncUserServiceClient) CreateUsers(ctx context.Context, in *CreateSyncUsersRequest, opts ...grpc.CallOption) (*SyncUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncUsersResponse)
	err := c.cc.Invoke(ctx, SyncUserService_CreateUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncUserServiceClient) UpdateUser(ctx context.Context, in *UpdateSyncUserRequest, opts ...grpc.CallOption) (*SyncUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncUserResponse)
	err := c.cc.Invoke(ctx, SyncUserService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncUserServiceClient) DeleteUser(ctx context.Context, in *DeleteSyncUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SyncUserService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncUserServiceClient) DeleteManyUser(ctx context.Context, in *DeleteManyUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, SyncUserService_DeleteManyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncUserServiceServer is the server API for SyncUserService service.
// All implementations must embed UnimplementedSyncUserServiceServer
// for forward compatibility.
type SyncUserServiceServer interface {
	CreateUser(context.Context, *CreateSyncUserRequest) (*SyncUserResponse, error)
	CreateUsers(context.Context, *CreateSyncUsersRequest) (*SyncUsersResponse, error)
	UpdateUser(context.Context, *UpdateSyncUserRequest) (*SyncUserResponse, error)
	DeleteUser(context.Context, *DeleteSyncUserRequest) (*empty.Empty, error)
	DeleteManyUser(context.Context, *DeleteManyUserRequest) (*empty.Empty, error)
	mustEmbedUnimplementedSyncUserServiceServer()
}

// UnimplementedSyncUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncUserServiceServer struct{}

func (UnimplementedSyncUserServiceServer) CreateUser(context.Context, *CreateSyncUserRequest) (*SyncUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSyncUserServiceServer) CreateUsers(context.Context, *CreateSyncUsersRequest) (*SyncUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUsers not implemented")
}
func (UnimplementedSyncUserServiceServer) UpdateUser(context.Context, *UpdateSyncUserRequest) (*SyncUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedSyncUserServiceServer) DeleteUser(context.Context, *DeleteSyncUserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedSyncUserServiceServer) DeleteManyUser(context.Context, *DeleteManyUserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteManyUser not implemented")
}
func (UnimplementedSyncUserServiceServer) mustEmbedUnimplementedSyncUserServiceServer() {}
func (UnimplementedSyncUserServiceServer) testEmbeddedByValue()                         {}

// UnsafeSyncUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncUserServiceServer will
// result in compilation errors.
type UnsafeSyncUserServiceServer interface {
	mustEmbedUnimplementedSyncUserServiceServer()
}

func RegisterSyncUserServiceServer(s grpc.ServiceRegistrar, srv SyncUserServiceServer) {
	// If the following call pancis, it indicates UnimplementedSyncUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncUserService_ServiceDesc, srv)
}

func _SyncUserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSyncUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncUserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncUserService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncUserServiceServer).CreateUser(ctx, req.(*CreateSyncUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncUserService_CreateUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSyncUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncUserServiceServer).CreateUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncUserService_CreateUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncUserServiceServer).CreateUsers(ctx, req.(*CreateSyncUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncUserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSyncUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncUserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncUserService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncUserServiceServer).UpdateUser(ctx, req.(*UpdateSyncUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncUserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSyncUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncUserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncUserService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncUserServiceServer).DeleteUser(ctx, req.(*DeleteSyncUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncUserService_DeleteManyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncUserServiceServer).DeleteManyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncUserService_DeleteManyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncUserServiceServer).DeleteManyUser(ctx, req.(*DeleteManyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyncUserService_ServiceDesc is the grpc.ServiceDesc for SyncUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_service.SyncUserService",
	HandlerType: (*SyncUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _SyncUserService_CreateUser_Handler,
		},
		{
			MethodName: "CreateUsers",
			Handler:    _SyncUserService_CreateUsers_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _SyncUserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _SyncUserService_DeleteUser_Handler,
		},
		{
			MethodName: "DeleteManyUser",
			Handler:    _SyncUserService_DeleteManyUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync_user.proto",
}
